### ISSUE TITLE
Docs site?

### ISSUE THREAD

**Issue by zlepper** [OctopusDeployLabs/terraform-provider-octopusdeploy#120]
I can see in the code that there are both docs and something that looks like a website, is there a URL for these? I would like to explore at a bit more high level, and navigating the docs folder manually is a bit difficult.

And apologies if I have missed something really obvious, but i believe i have looked at all the places i would expect a link to be.

**Comment by jbristowe** [comment]
Documentation is listed in `/docs` of the source. This gets picked up and formatted in the [Terraform Registry listing](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs). We'll be adding to the documentation with getting started guides very soon!

**Comment by zlepper** [comment]
I'm clearly blind, i could have sworn I had searched through the terraform site for anything about octopus, and could only find a reference to some really outdated version..

Either way, thank you very much :D

Mayhaps add a link in the GitHub repo, i believe there is an "official" link or something that can be added just under the repo title? :)

**Comment by jbristowe** [comment]
Hey @zlepper, just a quick update for you. We're adding more to the documentation. For the time being, this documentation will only be available in our [Terraform Registry listing](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs). So, keep checking there for updates.

**Comment by jbristowe** [comment]
I'm closing this issue since we'll be keeping the documentation up-to-date on the Terraform Registry page (as mentioned above).
