### ISSUE TITLE
The Id attribute of octopusdeploy_project returns a slug

### ISSUE THREAD

**Issue by cdhunt** [OctopusDeployLabs/terraform-provider-octopusdeploy#124]
**Steps to reproduce**
Consume octopusdeploy_project.resoruce_name.id

**Expected behavior**
Expect id to be in the format of Project-N, but get slug of name instead.

**Logs and other supporting information**
Given the following Terraform.

```hcl
resource "octopusdeploy_variable" "worker_pool_name_dev" {
  name       = "worker_pool_name"
  project_id = octopusdeploy_project.worker_nodes.id
  type       = "String"
  value = "dev"

  scope {
    environments = [octopusdeploy_environment.dev.id]
  }
}
```

I get the following Terraform plan where it is trying to change the project_id from the Id to the slug.

```
 ~ resource "octopusdeploy_variable" "worker_pool_name_dev" {
        id           = "797bbb7f-25ed-762d-a604-ff81e57ca14f"
      + is_sensitive = false
        name         = "worker_pool_name"
      ~ project_id   = "Projects-3" -> "worker-nodes"
        type         = "String"
        value        = "dev"
```

**Environment and versions:**
- OS: `Windows`
- Octopus Server Version: `2020.6.0-rc0001` (Cloud)
- Terraform Version: `0.13.6`
- Octopus Terraform Provider Version: provider[registry.terraform.io/octopusdeploylabs/octopusdeploy] 0.7.3

**Comment by jbristowe** [comment]
Very weird. I've tried to repro on my end, but I've been unsuccessful; I get a valid project ID (i.e. Projects-321). I'll keep investigating.

**Comment by cdhunt** [comment]
So, in my state file, the Id == the slug. Maybe this is an octopusdeploy_project importer bug.

```powershell
>terraform state show octopusdeploy_project.worker_nodes
# octopusdeploy_project.worker_nodes:
resource "octopusdeploy_project" "worker_nodes" {
    auto_create_release                  = false
    auto_deploy_release_overrides        = []
    default_guided_failure_mode          = "EnvironmentDefault"
    default_to_skip_if_already_installed = false
    deployment_process_id                = "deploymentprocess-Projects-3"
    description                          = "Deploy Octopus worker nodes"
    id                                   = "worker-nodes"
    included_library_variable_sets       = []
    is_disabled                          = false
    is_discrete_channel_release          = false
    is_version_controlled                = false
    lifecycle_id                         = "Lifecycles-2"
    name                                 = "Worker Nodes"
    project_group_id                     = "ProjectGroups-2"
    slug                                 = "worker-nodes"
    space_id                             = "Spaces-2"
    tenanted_deployment_participation    = "Untenanted"
    variable_set_id                      = "variableset-Projects-3"
   ...
```

**Comment by jbristowe** [comment]
Interesting. Do you mind telling him how you imported the project?

Example:

```
> terraform import octopusdeploy_project.worker_nodes Projects-123
```

**Comment by cdhunt** [comment]
By slug.

```
> terraform import octopusdeploy_project.worker_nodes worker-nodes
```

**Comment by jbristowe** [comment]
Ah, I understand.

Yeah, this is a bug. I'll investigate.

Thanks for submitting the issue!

**Comment by jbristowe** [comment]
For now, you can work around this issue by using the project ID when importing it (i.e. `Projects-321`).

**Comment by jbristowe** [comment]
Hey @cdhunt, I'm not sure if I can support this at the moment. Can you work around this issue by using the project ID?

**Comment by cdhunt** [comment]
I removed and reimported the state with the Product ID and it worked as expected.

**Comment by jbristowe** [comment]
I'm going to close this issue. Reading through the Terraform documentation, importing expects the resource ID. You can modify this but I'll add it to a later release (if possible).

**Comment by cdhunt** [comment]
When I was initially working on importing, I wasn't sure what Octopus considered an ID. For other providers, I generally pull IDs from the WebUI URL. In some cases, Octopus uses the `object-##` and in some cases, it uses the slug. So, I think if you make it clear in the documentation that any reference to ID is the `Object-##` formatted ID and you can get it by exporting the JSON from most pages then most people will never run into this.
