### ISSUE TITLE
octopusdeploy_lifecycles Data Source Does not Support - Name or Partial Name

### ISSUE THREAD

**Issue by JustinPullen** [OctopusDeployLabs/terraform-provider-octopusdeploy#129]
**Describe the bug**
octopusdeploy_lifecycles data source currently does not support passing Name or Partial name.

**Steps to reproduce**

data "octopusdeploy_lifecycles" "lifecycle" {
  name = "mylifecycle"
  #partial_name = "mylifecycle"
}

**Expected behavior**
I expect to be able to pass a name and receive a lifecycle object or list of objects back.

**Logs and other supporting information**
```Error: Unsupported argument

  on .terraform/modules/octpus_project/project.tf line 3, in data "octopusdeploy_lifecycles" "lifecycle":
   3:   partial_name = "mylifecycle"

An argument named "partial_name" is not expected here.```

```Error: Computed attributes cannot be set

  on .terraform/modules/octpus_project/project.tf line 3, in data "octopusdeploy_lifecycles" "lifecycle":
   3:   name = "mylifecycle"

Computed attributes cannot be set, but a value was set for "name".```

**Environment and versions:**
- OS: `OSX`
- Terraform Version: `0.14.5`
- Octopus Terraform Provider Version: `0.7.8`

**Additional context**
I am trying to upgrade to the new provider from 0.6.0

**Comment by jbristowe** [comment]
Oops! Sorry about that. Fixing now!

**Comment by JustinPullen** [comment]
@jbristowe any reason why Name is not implemented [here](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/d7fde5ae3460df511eee0e99d25d4502b8ea9ebf/octopusdeploy/data_source_lifecycles.go#L22)? Seems like other data sources implement it such as data_source_environement. 

Thanks for the update.

**Comment by jbristowe** [comment]
Simple: the Octopus API doesn't support it. The URI template specified for the Lifecycles API doesn't expose a `name` query:

```
"Lifecycles": "/api/<space-id>/lifecycles{/id}{?skip,take,ids,partialName}"
```

That stated, the query, `partialName` gives you (roughly) the same functionality.
