### ISSUE TITLE
Terraform crashes when creating listening tentacle deployment target

### ISSUE THREAD

**Issue by twozni** [OctopusDeployLabs/terraform-provider-octopusdeploy#131]
I'm running into an issue where Terraform crashes when creating a listening tentacle deployment target. When I try to create the resource below

```
resource "octopusdeploy_listening_tentacle_deployment_target" "deployment_target" {
  name                            = "${var.project_name} - Web"
  roles                           = var.roles
  tentacle_url                    = "https://${var.host}:${var.port}/"
  environments                    = [octopusdeploy_environment.environment.id]
  is_disabled                     = true
  operating_system                = "Windows"
  thumbprint                      = var.thumbprint
  certificate_signature_algorithm = "sha256RSA"

  depends_on = [octopusdeploy_environment.environment]
}
```

Terraform crashes and throws the following error

> octopusdeploy_environment.environment: Creating...
> octopusdeploy_environment.environment: Creation complete after 1s [id=Environments-878]
> octopusdeploy_listening_tentacle_deployment_target.deployment_target: Creating...
> 
> Error: rpc error: code = Unavailable desc = transport is closing
> 
> 
> panic: interface conversion: interface {} is nil, not []interface {}
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: goroutine 62 [running]:
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandEndpoint(0x0, 0x0, 0x8, 0x0)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_endpoint.go:10 +0xef3
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandDeploymentTarget(0xc000435680, 0x14a3bb6)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_deployment_target.go:13 +0xde
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandListeningTentacleDeploymentTarget(0xc000435680, 0xc000823608)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/schema_listening_tentacle_deployment_target.go:30 +0x5bc
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceListeningTentacleDeploymentTargetCreate(0x15aeac0, 0xc0005929c0, 0xc000435680, 0x132ae60, 0xc00011a000, 0xc0005e5e20, 0xf72332, 0xc0005e8580)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_listening_tentacle_deployment_target.go:25 +0x52
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000285080, 0x15aea40, 0xc0005a4bc0, 0xc000435680, 0x132ae60, 0xc00011a000, 0x0, 0x0, 0x0)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/resource.go:285 +0x1f4
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000285080, 0x15aea40, 0xc0005a4bc0, 0xc000142af0, 0xc0005e8580, 0x132ae60, 0xc00011a000, 0x0, 0x0, 0x0, ...)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/resource.go:396 +0x674
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00008aa60, 0x15aea40, 0xc0005a4bc0, 0xc0004f4d20, 0xc0005a4bc0, 0x0, 0x15bab80)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.1/helper/schema/grpc_provider.go:955 +0x8ef
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0007338e0, 0x15aea40, 0xc0005a4bc0, 0xc000142930, 0xc0007338e0, 0xc0005c6630, 0xc00052fba0)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xb8
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x144fc00, 0xc0007338e0, 0x15aeb00, 0xc0005c6630, 0xc0005925a0, 0x0, 0x15aeb00, 0xc0005c6630, 0xc0006a8000, 0x438)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b0540, 0x15b8880, 0xc00040f500, 0xc000174900, 0xc00035f500, 0x1a9edc0, 0x0, 0x0, 0x0)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        google.golang.org/grpc@v1.35.0/server.go:1217 +0x522
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: google.golang.org/grpc.(*Server).handleStream(0xc0000b0540, 0x15b8880, 0xc00040f500, 0xc000174900, 0x0)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        google.golang.org/grpc@v1.35.0/server.go:1540 +0xd25
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000096230, 0xc0000b0540, 0x15b8880, 0xc00040f500, 0xc000174900)
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        google.golang.org/grpc@v1.35.0/server.go:878 +0xa8
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
> 2021-02-03T14:09:15.542-0600 [DEBUG] plugin.terraform-provider-octopusdeploy_v0.7.9.exe:        google.golang.org/grpc@v1.35.0/server.go:876 +0x1fd
> 2021-02-03T14:09:15.547-0600 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
> 2021/02/03 14:09:15 [DEBUG] octopusdeploy_listening_tentacle_deployment_target.deployment_target: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
> 2021/02/03 14:09:15 [TRACE] EvalMaybeTainted: octopusdeploy_listening_tentacle_deployment_target.deployment_target encountered an error during creation, so it is now marked as tainted
> 2021/02/03 14:09:15 [TRACE] EvalWriteState: removing state object for octopusdeploy_listening_tentacle_deployment_target.deployment_target
> 2021/02/03 14:09:15 [TRACE] EvalApplyProvisioners: octopusdeploy_listening_tentacle_deployment_target.deployment_target has no state, so skipping provisioners
> 2021/02/03 14:09:15 [TRACE] EvalMaybeTainted: octopusdeploy_listening_tentacle_deployment_target.deployment_target encountered an error during creation, so it is now marked as tainted
> 2021/02/03 14:09:15 [TRACE] EvalWriteState: removing state object for octopusdeploy_listening_tentacle_deployment_target.deployment_target
> 2021/02/03 14:09:15 [TRACE] vertex "octopusdeploy_listening_tentacle_deployment_target.deployment_target": visit complete
> 2021/02/03 14:09:15 [TRACE] dag/walk: upstream of "octopusdeploy_lifecycle.lifecycle" errored, so skipping
> 2021/02/03 14:09:15 [TRACE] dag/walk: upstream of "octopusdeploy_project.project" errored, so skipping
> 2021/02/03 14:09:15 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
> 2021/02/03 14:09:15 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/octopusdeploylabs/octopusdeploy\"] (close)" errored, so skipping
> 2021/02/03 14:09:15 [TRACE] dag/walk: upstream of "root" errored, so skipping
> 2021/02/03 14:09:15 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
> 2021/02/03 14:09:15 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 50
> 2021/02/03 14:09:15 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
> 2021/02/03 14:09:15 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
> 2021/02/03 14:09:15 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
> 2021-02-03T14:09:15.556-0600 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/octopusdeploylabs/octopusdeploy/0.7.9/windows_amd64/terraform-provider-octopusdeploy_v0.7.9.exe pid=39144 error="exit status 2"
> 2021-02-03T14:09:15.556-0600 [DEBUG] plugin: plugin exited

I tried using **octopusdeploy_deployment_target** as well but saw the same issue with that resource. 

> Terraform v0.14.4
> provider registry.terraform.io/octopusdeploylabs/octopusdeploy v0.7.9
> OS: Windows

**Comment by jbristowe** [comment]
Thank you very much for this bug report. I'll take a look at it today.
