### ISSUE TITLE
[Feature] runbook resource

### ISSUE THREAD

**Issue by MaxDeg** [OctopusDeployLabs/terraform-provider-octopusdeploy#135]
Hello,

Do you plan to add resource to create runbooks associated with projects? This is the last bit missing avoiding us to go fully with terraform to support our Octopus installation.

Thank you

**Comment by ajaychoudhary-bcg** [comment]
@jbristowe  do we know by when it will be available?

**Comment by pemaxim** [comment]
@jbristowe Is there any feedback here? It would be great to have `runbook` and `runbook_process` resources in the provider. Thanks.

**Comment by jbristowe** [comment]
Sorry for the delay! I've just wrapped up support for applying Terraform templates. I'll tackle this issue now. Expect an update this week.

**Comment by mitchelldavis44** [comment]
Bump, any update on runbooks?

**Comment by bfagerhed2** [comment]
We're in the process of taking Octopus into use as Deploy tool for our company and in the plan make all CI/CD pipelines as code. 
This terraform provider looks nice but its missing one important feature: configuring runbooks with terraform. 
I think it is a very important feature in order to get everything configured as code.
Any updates on when the support could be added to this provider?

**Comment by mitchelldavis44** [comment]
any update on this issue?

**Comment by DamienDaco** [comment]
Hello @jbristowe 
I would like to know if adding this feature is still being worked on? Or planned in the near future?
My company would really like to implement Terraform to manage Octopus (It's awesome!).
However we're missing this crucial resource, and this could compromise the adoption of the terraform/octopus provider.
Regards,

**Comment by jbristowe** [comment]
I'm in the midst of wrapping up support for project triggers. Runbook management will be next. 👍

**Comment by geoffreyprice** [comment]
Just checking to see if there is an ETA for this feature? Thank you!

**Comment by bfagerhed2** [comment]
Same question here. It would be really great to have to runbooks configured with this provider. I used the the REST api to configure runbooks (using python), but I would preferer using terraform since I got almost everything else configured with this provider

**Comment by geoffreyprice** [comment]
I see some activity on this removing it from a todo and unassigning people. Is this still a planned feature? Thank you!

**Comment by JustinPullen** [comment]
This ticket has fallen stale but there are many still waiting for and working around this as one of the last major portions of our implementation that is not done via code.

**Comment by haskins60** [comment]
Has this fallen off the radar?  As mentioned in previous comments, we would love to see some traction on this capability.
