### ISSUE TITLE
Terraform crashes when removing OD sensitive variables from project

### ISSUE THREAD

**Issue by OmarSalka** [OctopusDeployLabs/terraform-provider-octopusdeploy#138]
Hi,

Terraform crashes when I try to remove an OD sensitive variable from my terraform configuration files. I had to manually remove the sensitive OD variables from the tfstate file and then manually remove them from the OD project

I get the following error:
```
Error: cannot find the item
```

Here's when terraform crashes when i try to rerun it hoping that it would fix itself:
```
rpc error: code = Unavailable desc = transport is closing
rpc error: code = Canceled desc = context canceled
```
and it would keep repeating those two lines

**Comment by jbristowe** [comment]
Hey @OmarSalka! Thanks for your bug report.

After removing the sensitive value from your configuration, when are you seeing the error? During `terraform plan` or `terraform apply`?

**Comment by OmarSalka** [comment]
since i script the terraform steps i go straight from terraform init to terraform apply; thus the error happens on apply

**Comment by jbristowe** [comment]
Hey @OmarSalka. 👋 Numerous changes to variable resource management appear to have resolved this behaviour. Please download the latest release and confirm. Thanks!

**Comment by jbristowe** [comment]
This issue appears to be resolved. Closing.
