### ISSUE TITLE
Project variable always has planned changes

### ISSUE THREAD

**Issue by ecca** [OctopusDeployLabs/terraform-provider-octopusdeploy#143]
**Describe the bug**
Provider wants to set project variable scope to null but defaults to array ( on server api ? )

**Steps to reproduce**
1. Setup provider
2. Create a project variable
3. Run `terraform plan` again after created feed, planned changes should occur

```javascript
resource "octopusdeploy_variable" "frontend_variable_testvariable" {
  name       = "test_variable"
  project_id = "PROJECT-ID"
  type       = "String"
  value      = "1"

  scope {
    environments = [
      "ENVIRONMENT-ID"
    ]
  }
}
```

**Expected behavior**
When created, planned changes should not occur everytime on unchanged data.

**Logs and other supporting information**
```javascript
  ~ resource "octopusdeploy_variable" "frontend_variable_testvariable" {
        id           = "7196d800-f53f-45e3-bb93-01d02ead9599"
        name         = "test_variable"
        # (4 unchanged attributes hidden)

      - scope {
          - actions            = [] -> null
          - channels           = [] -> null
          - environments       = [] -> null
          - machines           = [] -> null
          - parent_deployments = [] -> null
          - private            = [] -> null
          - process_owners     = [] -> null
          - projects           = [] -> null
          - roles              = [] -> null
          - target_roles       = [] -> null
          - tenant_tags        = [] -> null
          - tenants            = [] -> null
          - triggers           = [] -> null
          - users              = [] -> null
        }
    }
```

**Environment and versions:**
- OS: Windows
- Octopus Server Version: 2020.5 (Build 280)
- Terraform Version: v0.14.8
- Octopus Terraform Provider Version: v0.7.13

**Comment by jbristowe** [comment]
Thanks for submitting this issue.

I believe this behaviour has been fixed in the latest release of the provider. Would you mind testing it out on [v0.7.14](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/releases/tag/v0.7.14) ([Terraform Registry](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest))? Thanks!

**Comment by ecca** [comment]
Thank you for the swift reply @jbristowe

Unfortunately, the issue seems to stand when testing on terraform v.0.7.14 with upgraded octopusdeploy at 2020.6.4722. Also still applies to #142

**Comment by jbristowe** [comment]
@ecca Please confirm this behaviour still exists (or not) with the latest release. Thanks!

**Comment by ecca** [comment]
@jbristowe #172 is blocking my testing 😄

**Comment by ecca** [comment]
Can't replicate in 0.7.33, thanks 😄
