### ISSUE TITLE
Add a resource for creating Step Templates

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeployLabs/terraform-provider-octopusdeploy#145]
**Is your feature request related to a problem? Please describe.**
Currently, defining and managing step templates is unsupported. (For ability to **consume** Step Templates in Deployment Processes, see #137)

As a user, I would like to have them supported by the Terraform Provider for Octopus Deploy so that I may manage them through configuration with Terraform.

**Describe the solution you'd like**
A new resource (i.e. `octopusdeploy_step_template`) that provides an ability to create, update and destroy Step Templates through configuration with Terraform.

**Describe alternatives you've considered**
No alternatives are available at the moment.

**Additional context**
This request was originally made by a member of the Octopus Deploy Community Slack.

**Comment by ajaychoudhary-bcg** [comment]
do we know by when it will be available?

**Comment by ajaychoudhary-bcg** [comment]
Any update on this?

**Comment by DamienDaco** [comment]
I would also like to know if step templates will be supported in the future, cheers.

**Comment by k0kazpt** [comment]
This would be a great feature, as most deployment processes use step templates. Currently the only way I know around this is to call the API directly using a null resource.

**Comment by tdeblsh** [comment]
Would be really appreciated

**Comment by Scott-Emberson** [comment]
@jbristowe any idea when this feature could be available?

**Comment by zentron** [comment]
Closing as duplicate of https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/137
