### ISSUE TITLE
User Role in team resource

### ISSUE THREAD

**Issue by ajaychoudhary-bcg** [OctopusDeployLabs/terraform-provider-octopusdeploy#150]
**Is your feature request related to a problem? Please describe.**
User Role is not available as part of team resource creation. This is available from UI but not in terraform.

**Describe the solution you'd like**
User role list parameter in team resource.

**Describe alternatives you've considered**
We are updating it manually. 

**Additional context**
None

**Comment by evan-cleary** [comment]
@ajaychoudhary-bcg I've actually put up a PR in the underlying go api library to add support for the ScopedUserRoles (the resource that controls team user roles). I plan on putting up a PR for the provider once that is done.

See: https://github.com/OctopusDeploy/go-octopusdeploy/pull/51

**Comment by ajaychoudhary-bcg** [comment]
@evan-cleary  Thanks Mate, looks like your PR is merged. Please update terraform provider so that we can use it.

**Comment by ajaychoudhary-bcg** [comment]
@evan-cleary Any update on this?

**Comment by ajaychoudhary-bcg** [comment]
@evan-cleary  Could you please help in getting this resolved.

**Comment by evan-cleary** [comment]
@ajaychoudhary-bcg best thing I can tell you is to clone the repo, build a custom binary and install it as a local provider: https://www.terraform.io/docs/language/providers/requirements.html#in-house-providers

**Comment by ajaychoudhary-bcg** [comment]
Is it not possible to merge this fix in and provider as part of resource?
