### ISSUE TITLE
create team not working inside space or similar

### ISSUE THREAD

**Issue by richas722** [OctopusDeployLabs/terraform-provider-octopusdeploy#151]
**Describe the bug**
While automating creation of teams- the spaceId is not working as expected. Scope of a team is for System however it should be confined within the given spaceID.

**code:**

**main.tf:**

terraform {
  required_providers {
    octopusdeploy = {
      source  = "OctopusDeployLabs/octopusdeploy"
    }
  }
}

provider "octopusdeploy" {
  address  = var.address
  api_key   = var.api_key
  space_id = var.space_id
}

resource "octopusdeploy_team" "team-demo" {
    name = var.name
    description = var.description
    users       = data.octopusdeploy_users.example[*].users[0].id
}

**data.tf:**

data "octopusdeploy_users" "example" {

  count = length(var.users)

  filter = var.users[count.index]
  skip = 0
  take = 1
}

**tfvars:**

address         = <URL>
api_key  = <API KEy>
space_id        = "Spaces-90"
name            = "Test-team"
description     = "This is a test team"
#users           = ["<emailID>"]

**Comment by ajaychoudhary-bcg** [comment]
@jbristowe Currently space id is readonly. are we making it read-write argument? When this will be release?

**Comment by jbristowe** [comment]
I've published a new release, which incorporates these changes. Let me know how it goes.

**Comment by ajaychoudhary-bcg** [comment]
@jbristowe It still created System Team. Space_id is read-only so we can't set it, although provider has space id.

**Comment by ajaychoudhary-bcg** [comment]
@jbristowe  Its working. Thanks mate.
