### ISSUE TITLE
Product Group re-adding env everytime on terraform plan/apply

### ISSUE THREAD

**Issue by ajaychoudhary-bcg** [OctopusDeployLabs/terraform-provider-octopusdeploy#157]
**Describe the bug**
Product Group re-adding env everytime on terraform plan/apply

**Steps to reproduce**
1. create env and product group
2. give reference of env in product group
3. run terraform init and terraform plan/apply
4. Env are re-added on every plan/apply

**Expected behavior**
Env should be added only once 

**Logs and other supporting information**
~ resource "octopusdeploy_project_group" "this" {
      ~ environments = [
          + "Environments-265",
          + "Environments-266",
          + "Environments-267",
        ]
        id           = "ProjectGroups-267"
        name         = "dummy"
        # (1 unchanged attribute hidden)
    }

**Screenshots**

**Environment and versions:**
- OS: [e.g. `Windows`, `Linux`, `OSX`] Linux
- Octopus Server Version: [e.g. `2019.6.1`] latest
- Terraform Version: [e.g. `0.12.4`] 0.14.7
- Octopus Terraform Provider Version: [e.g. `0.2.0`] 0.7.17

**Additional context**

**Comment by jbristowe** [comment]
Hey @ajaychoudhary-bcg! 👋 Thanks for submitting this issue.

This attribute is a carry-over of version 2.6.5, which dated back to October 2014. Environments are now controlled by lifecycles.

This attribute will be removed.
