### ISSUE TITLE
Step actions ordering issue: run_script_action always added after action

### ISSUE THREAD

**Issue by pemaxim** [OctopusDeployLabs/terraform-provider-octopusdeploy#189]
**Describe the bug**

`run_script_action` action is always added to the end of actions list. Example:

```
step {
  name = "My Step"
  
  action {
     name = "Action One"
  }

  run_script_action {
    name = "Action Two"
  }

  action {
    name = "Action Three"
  }

}
```

Process Step will have the following order:

My Step:
1. Action One
2. Action Three
3. Action Two

**Environment and versions:**
- OS: `Linux`
- Octopus Server Version: `2020.5.0`
- Terraform Version: `0.14.9`
- Octopus Terraform Provider Version: `0.7.36`

**Comment by zentron** [comment]
This has been fixed as of https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/525
