### ISSUE TITLE
octopusdeploy_feed resource using AwsElasticContainerRegistry type returns an error

### ISSUE THREAD

**Issue by Littletiger** [OctopusDeployLabs/terraform-provider-octopusdeploy#190]
I'm trying to add an AWS feed using the terraform below:

```
 resource "octopusdeploy_feed" "aws" {
   name         = "aws feed"
   feed_uri     = ""
   feed_type    = "AwsElasticContainerRegistry"
   is_enhanced_mode = false
   download_attempts = 5
   download_retry_backoff_seconds = 10
   access_key   = "xxxxxx"
   secret_key   = "xxxxxx"
 }
```
The plan comes back fine however It outputs the following error after you accept the apply:
```

Error: Octopus API error: Value cannot be null. (Parameter 'key') []
  with octopusdeploy_feed.aws,
   on main.tf line 36, in resource "octopusdeploy_feed" "aws":
   36: resource "octopusdeploy_feed" "aws" {
```

I can create this feed manually with no errors, I've looked through the documentation and couldn't figure out what the issue is, any help will be greatly appreciated.

OS: Linux
Octopus Server Version: 2021.1 (7006)
Terraform Version: 0.15.3
Octopus Terraform Provider Version: 0.7.36

**Comment by jbristowe** [comment]
Please use `octopusdeploy_aws_elastic_container_registry` instead.

Documentation is [here](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/aws_elastic_container_registry).
