### ISSUE TITLE
data.octopusdeploy_feeds

### ISSUE THREAD

**Issue by mbenson** [OctopusDeployLabs/terraform-provider-octopusdeploy#200]
**Is your feature request related to a problem? Please describe.**
For any item that should be configured by ID, there should IMO be a data source permitting the ID to be derived from the meaningful name.

**Describe the solution you'd like**
I would recommend that the provider define a data source along the same lines as other similar data sources, e.g. `octopusdeploy_lifecycles`.

**Describe alternatives you've considered**
Referencing the feed by (meaningless) ID.

**Additional context**
N/A

**Comment by jbristowe** [comment]
Thanks for your issue, @mbenson. I'm a bit confused. The data source, [`octopusdeploy_feeds`](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/data-sources/feeds) exposes a `partial_name` property for retrieving feeds whose name is a partial match for the query. Is this what you're after?

**Comment by mbenson** [comment]
I only looked under the Resources and Data Sources menu items and never noticed "Feeds". It is working just as I requested/expected/need, and this issue can and should be closed as invalid. Thanks!
