### ISSUE TITLE
Apply Terraform Template Action does not set use_instance_role

### ISSUE THREAD

**Issue by kamal-mahmassani-cko** [OctopusDeployLabs/terraform-provider-octopusdeploy#234]
**Describe the bug**
When using the `apply_terraform_template_action` resource,  the `use_instance_role` value is not correctly set in Octopus.

**Steps to reproduce**

```terraform
step {
    condition           = "Success"
    name                = "Apply Blue"
    package_requirement = "LetOctopusDecide"
    start_trigger       = "StartAfterPrevious"

    apply_terraform_template_action {
      name          = "Apply Blue"
      run_on_server = true

      advanced_options {
        allow_additional_plugin_downloads = true
        apply_parameters                  = "-var \"image_tag_blue=#{Image.Tag.New}\" -var \"image_tag_green=#{Image.Tag.Previous}\"" # TODO VAR
        init_parameters                   = "--backend-config=\"./backend.config\" -reconfigure"
      }

      aws_account {
        region            = "#{AWS.Region}"
        use_instance_role = true

        role {
          arn               = "#{Iam.Account.Role}"
          role_session_name = "#{Octopus.ProjectGroup.Id}"
          session_duration  = 3600
        }
      }

      template {
        directory                       = var.package.terraform_template_directory
        run_automatic_file_substitution = true
        additional_variable_files       = var.package.terraform_variable_file
        target_files                    = "**\\*.config\n**\\*.tfvars.json"
      }

      primary_package {
        package_id = var.package.id
        feed_id    = local.feed_id
      }

      condition   = "Success"
      is_required = true
    }
  }
```
Ends up with no option chosen on the relevant radio button in Octopus:

![image](https://user-images.githubusercontent.com/66256462/130800821-5476d6aa-2921-45e0-9137-f8c7729a7623.png)

**Expected behavior**
The relevant option should be chosen in the radio button:
![image](https://user-images.githubusercontent.com/66256462/130801190-f7db592a-2c77-4230-9b50-dcf6781c2434.png)

**Logs and other supporting information**
It *may* be due to an issue with the serialization of boolean `true` as `"true"` instead of `"True"`.

**Environment and versions:**
- Octopus Server Version: 2021.1
- Terraform Version: 0.13.5
- Octopus Terraform Provider Version: 0.7.55

**Additional context**

**Comment by jbristowe** [comment]
Great catch! I'll fix this now.
