### ISSUE TITLE
`run_script_action` not properly setting execution location

### ISSUE THREAD

**Issue by evan-cleary** [OctopusDeployLabs/terraform-provider-octopusdeploy#248]
**Describe the bug**
Only the generic Deployment Action is able to specify the worker pool that the action will execute on. Most actions support setting a target worker pool utilizing an ID or a variable name in the UI. As more actions have been moved to defined action blocks they have subsequently lost this capability. In some cases this causes the `run_on_server` property to not function properly. For example a `run_script_action` block with `run_on_server = true` create a script action that still runs on deployment targets. Other actions properly select the default worker pool in this same condition.

**Steps to reproduce**
1. Set up a project
2. Create a deployment process with a single step with a `run_script_action` block
3. Apply terraform
4. Check Deployment Process in UI

**Expected behavior**
1. UI should show that the deployment step is to run on an octopus server/worker targeting the default worker pool

**Logs and other supporting information**
Add the output of running `tf plan` or `tf apply` along with any errors in the Octopus Server logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/1305289/133479096-94fe877c-5847-4f86-8eda-87d9c1f9b5a9.png)

**Environment and versions:**
- OS: Linux
- Octopus Server Version: 2021.2.7428
- Terraform Version: 0.14.7
- Octopus Terraform Provider Version: 0.7.58

**Additional context**
Action Definition for above screenshot
```json
{
	"Actions": [
		{
			"Id": "ecf38354-7a28-4188-9343-d0f641ebb7b6",
			"Name": "Docker Reference",
			"ActionType": "Octopus.Script",
			"Notes": null,
			"IsDisabled": false,
			"CanBeUsedForProjectVersioning": true,
			"IsRequired": true,
			"WorkerPoolId": null,
			"Container": {
				"Image": null,
				"FeedId": null
			},
			"WorkerPoolVariable": null,
			"Environments": [],
			"ExcludedEnvironments": [],
			"Channels": [],
			"TenantTags": [],
			"Packages": [],
			"Condition": "Success",
			"Properties": {
				"Octopus.Action.EnabledFeatures": "Octopus.Features.SubstituteInFiles,Octopus.Features.SubstituteInFiles,Octopus.Features.SubstituteInFiles,Octopus.Features.SubstituteInFiles",
				"Octopus.Action.RunOnServer": "True",
				"Octopus.Action.Script.ScriptBody": "echo 1",
				"Octopus.Action.Script.ScriptSource": "Inline",
				"Octopus.Action.Script.Syntax": "Bash",
				"Octopus.Action.SubstituteInFiles.Enabled": "True"
			},
			"Links": {}
		}
	]
}
```

**Comment by mbenson** [comment]
My testing shows that this is a bug in `0.7.58`, probably resulting from the boolean serialization fixes. My simple TF script to reproduce:

```
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    octopusdeploy = {
      source  = "OctopusDeployLabs/octopusdeploy"
      version = "0.7.58"
    }
  }
}

variable "octopus_address" {
  type    = string
}

variable "octopus_api_key" {
  type    = string
}

variable "octopus_space_id" {
  type    = string
}

provider "octopusdeploy" {
  address    = var.octopus_address
  api_key    = var.octopus_api_key
  space_id = var.octopus_space_id
}

variable "octopus_lifecycle_id" {
  type = string
}

variable "octopus_project_group_id" {
  type = string
}

variable "octopus_project_name" {
  type = string
}

resource "octopusdeploy_project" "project" {
  name                              = var.octopus_project_name
  project_group_id                  = var.octopus_project_group_id
  lifecycle_id                      = var.octopus_lifecycle_id
  included_library_variable_sets    = []
}

resource "octopusdeploy_deployment_process" "deployment_process" {
  project_id = octopusdeploy_project.project.id
  step {
    name      = "Run script"
    condition = "Success"
    run_script_action {
      name                               = "Run script"
      can_be_used_for_project_versioning = false
      condition                          = "Success"
      is_disabled                        = false
      is_required                        = true
      run_on_server                      = true
      script_syntax                      = "Bash"
      script_source                      = "Inline"
      script_body                        = "echo foo"
    }
  }
}
```

**Comment by davidkarim** [comment]
I have also encountered this issue. Is anyone looking into this?

**Comment by jbristowe** [comment]
Confirmed! This is a bug. Thank you very much for reporting it! 👍  I'll implement a fix.

**Comment by davidkarim** [comment]
Thanks John. I will definitely be confirming any fix as soon as it's available. I do also believe that the worker_pool_id argument may be necessary; it currently states that this argument is not expected inside of the run_script_action block.

**Comment by jbristowe** [comment]
Hey @davidkarim! 👋 Thanks for that. I've published a new version of the provider to the Terraform Registry. Let me know how it goes.

**Comment by davidkarim** [comment]
Thanks John. Looks like that did the trick.
