### ISSUE TITLE
Octopus API error: The given key 'Octopus.ControlType' was not present in the dictionary

### ISSUE THREAD

**Issue by osipovdaniil** [OctopusDeployLabs/terraform-provider-octopusdeploy#249]
**Describe the bug**
Error `Error: Octopus API error: The given key 'Octopus.ControlType' was not present in the dictionary. []` when I create a resource `octopusdeploy_variable`

I have simple terraform manifests:

```
resource "octopusdeploy_variable" "kube_web_view" {
  name             = "Test"
  type               = "String"
  project_id     = "Projects-1083"
  value             = "123"
}
```

**Logs and other supporting information**

My terraform plan:

```
# octopusdeploy_variable.kube_web_view will be created
  + resource "octopusdeploy_variable" "kube_web_view" {
      + encrypted_value = (known after apply)
      + id              = (known after apply)
      + is_editable     = true
      + is_sensitive    = false
      + key_fingerprint = (known after apply)
      + name            = "Test"
      + owner_id        = "Projects-1083"
      + type            = "String"
      + value           = "123"
    }
```

When i run terraform apply, i got an error:

`Error: Octopus API error: The given key 'Octopus.ControlType' was not present in the dictionary. []`

**Expected behavior**
i want to just create a variable in my octopus project

**Screenshots**
<img width="951" alt="Снимок экрана 2021-09-17 в 14 57 40" src="https://user-images.githubusercontent.com/73994399/133778946-a27c3ff9-fa05-4ae1-b7b8-2311a51049c9.png">

**Environment and versions:**
- Terraform Version: [0.13.2]
- Octopus Terraform Provider Version: [octopusdeploylabs/octopusdeploy v0.7.58]

**Additional context**
Thanks for any help

**Comment by osipovdaniil** [comment]
Sorry, probably this is not a problem in the provider, but in the octopus project. Because in another project the variable is created

**Comment by JustinPullen** [comment]
@osipovdaniil what was the final issue here?
