### ISSUE TITLE
`octopusdeploy_ssh_key_account` not setting private key details (file or passphrase) correctly

### ISSUE THREAD

**Issue by onematchfox** [OctopusDeployLabs/terraform-provider-octopusdeploy#250]
**Describe the bug**
Easiest seen in this line of code https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/5795e223d85487a896a9c38475ab7af70817dd3a/octopusdeploy/schema_ssh_key_account.go#L15

FYI: The deprecated `octopusdeploy_account` suffers from a similar issue. See: 
https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/5795e223d85487a896a9c38475ab7af70817dd3a/octopusdeploy/schema_account_resource.go#L68-L70

Also, out of interest sake, is there a reason a filename needs to be marked as `sensitive`? Seems like overkill, no?
Edit: Figured out that `private_key_file` is not actually a file but actually the `key` (I.e. `base64` encoded text of the private key in PEM format).

**Comment by zentron** [comment]
This issue has been resolves as part of a breaking change in https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/642. and shipped in `v0.21.1`
