### ISSUE TITLE
Provider doc - `octopusdeploy_lifecycles`

### ISSUE THREAD

**Issue by jebl01** [OctopusDeployLabs/terraform-provider-octopusdeploy#260]
The data source octopusdeploy_lifecycles does not seem to support `id`
https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/data-sources/lifecycles#optional

**Comment by johnsimons** [comment]
This is by design.
Use the `ids` list field with a single id.
