### ISSUE TITLE
Request To Add `worker_pool_id` and Inline Script Feature To `run_kubectl_script`

### ISSUE THREAD

**Issue by petersin0422** [OctopusDeployLabs/terraform-provider-octopusdeploy#284]
**Is your feature request related to a problem? Please describe.**
I am not sure why the `run_kubectl_script` deployment step forces you to use `package` as the script source while it is allowed to use `inline` in the API. Trying to overwrite this behavior with `properties = {"Octopus.Action.Script.ScriptSource" = "Inline"}` wouldn't work either. It's also weird that the step also has `script_source` as an option, which is completely ignored in this case. 

Additionally, while there is a `run_in_server` option, the `worker_pool_id` option is missing completely.

**Describe the solution you'd like**
Implement the following in `run_kubectl_script` action:

- Inline script support: `script_source`, `script_syntax`, `script_body`
- `worker_pool_id`

**Describe alternatives you've considered**
None, using the generic `action` step wouldn't help either.

**Comment by zentron** [comment]
These properties have [since been added](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/0.14.6/docs/resources/runbook_process#nested-schema-for-steprun_kubectl_script_action)
