### ISSUE TITLE
Getting Guide -- Setup is Confusing

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeployLabs/terraform-provider-octopusdeploy#296]
https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/guides/2-setup

This page doesn't make any sense. Why is this included in the documentation for the Terraform Provider?

**Comment by hnrkndrssn** [comment]
I've been working on refactoring the guides so will look at removing this page (or rewriting it so it makes sense to be included)
