### ISSUE TITLE
Add worker pool resource and/or datasource

### ISSUE THREAD

**Issue by tcarrondo** [OctopusDeployLabs/terraform-provider-octopusdeploy#301]
**Describe the solution you'd like**
It would be nice to have a resource to create/manage worker pools.

**Describe alternatives you've considered**
Currently we are using an API call to retrieve the worker pool, manually created, id and re use it (via local or var) along the code.

**Comment by jbristowe** [comment]
Hey @tcarrondo! You can create dynamic and static worker pool resources through the Terraform Provider. Unfortunately, the documentation hasn't been synced with the Terraform Registry.

[Dynamic Worker Pool](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/master/docs/resources/dynamic_worker_pool.md)
[Static Worker Pool](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/master/docs/resources/static_worker_pool.md)

We'll ship a new version (soon) that will include these in the documentation.

**Comment by tcarrondo** [comment]
It's working! thanks
