### ISSUE TITLE
Feature: Space Data Source

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeployLabs/terraform-provider-octopusdeploy#324]
Currently, the data source, `octopusdeploy_spaces` provides a context for searching against a collection of space resources. This is non-optimal for searching against a singular space where one (and only one) result is expected.

This issue requests the creation of a new data source: `octopusdeploy_space`. This would provide an ability to search for one (and only one) space by its `name` property.

**Comment by johnsimons** [comment]
This seems to be implemented nin later versions.
```tf
data "octopusdeploy_space" "mine" {
  name = "John"
}

output "space_id" {
  value = data.octopusdeploy_space.mine.id
}
```
