### ISSUE TITLE
Documentation - Project Resource Requires Space Id

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeployLabs/terraform-provider-octopusdeploy#346]
**Describe the bug**
The Octopus resource Project, requires space_id to be configured however the documentation says it's optional.

**Steps to reproduce**
```
resource "octopusdeploy_project" "project" {
  
  lifecycle_id        = "Lifecycles-1"
  name                = "Test TF3"
  project_group_id    = "ProjectGroups-1"
  #space_id            = "Default"
}
```

**Expected behavior**
The documentation should reflect the required resources accurately.

**Logs and other supporting information**
│ Error: validation failure in Update; Key: 'Project.SpaceID' Error:Field validation for 'SpaceID' failed on the 'required' tag

**Screenshots**
<img width="1172" alt="Screen Shot 2022-03-01 at 11 58 51" src="https://user-images.githubusercontent.com/78527975/156090403-04efea7c-fa55-4f89-93aa-b326a5c860b3.png">
<img width="738" alt="Screen Shot 2022-03-01 at 11 59 09" src="https://user-images.githubusercontent.com/78527975/156090427-ec45f78b-cba0-4f48-85fb-9ca0c87efcfd.png">

**Additional context**
[Documentation Link](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/project#required)

**Comment by mbenson** [comment]
With a _bisect_ approach, I determined that the regression began with `0.7.65`; i.e. if you revert the provider version in the following example to `0.7.64` the plan can be applied successfully:

```
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    octopusdeploy = {
      source  = "OctopusDeployLabs/octopusdeploy"
      version = "0.7.65"
    }
  }
}

variable "octopus_address" {
  type = string
}

variable "octopus_api_key" {
  type = string
}

variable "octopus_space_id" {
  type = string
}

variable "octopus_lifecycle_id" {
  type = string
}

variable "octopus_project_group_id" {
  type = string
}

variable "octopus_project_name" {
  type = string
}

provider "octopusdeploy" {
  address  = var.octopus_address
  api_key  = var.octopus_api_key
  space_id = var.octopus_space_id
}

resource "octopusdeploy_project" "project" {
  name             = var.octopus_project_name
  project_group_id = var.octopus_project_group_id
  lifecycle_id     = var.octopus_lifecycle_id
}
```

**Comment by jbristowe** [comment]
After reviewing the behaviour associated with this issue, I agree; this is a bug and the underlying API client has been modified to return to the previous implementation. Going forward, the `space_id` attribute will be optional.
