### ISSUE TITLE
Extracted path not showing any files in another step template

### ISSUE THREAD

**Issue by dhanrajshimpi123** [OctopusDeployLabs/terraform-provider-octopusdeploy#365]
We have created step template in that extracted package and set the output variable

Step 1:
PackageName - Is the input package parameter name and extracted it in package references 

Set-OctopusVariable -name "ExtractPath" -value $OctopusParameters["Octopus.Action.Package[PackageName].ExtractedPath"]

also able to get file C:\tools\Octopus\Work\20220405103646-108864-374\PackageName\local.settings.json 

Step 2 :
In this we are trying to access extracted path using output variable  name "ExtractPath"

Write-Host $OctopusParameters["Octopus.Action[$PackageExtractionStepName].Output.ExtractPath"] 

In step 2 we are getting package path but If we try to access C:\tools\Octopus\Work\20220405103646-108864-374\PackageName\local.settings.json  file from extracted path then it's showing not found

**Comment by johnsimons** [comment]
This does not seem to be related to terraform, if you having issues with Octopus Server please contact support.
