### ISSUE TITLE
Please add Google Account types to the variable resource

### ISSUE THREAD

**Issue by twerthi** [OctopusDeployLabs/terraform-provider-octopusdeploy#378]
**Is your feature request related to a problem? Please describe.**
The `octopusdeploy_variable` lists `type` for AmazonWebServiceAccount and AzureAccount, but does not seem to have a type for Google accounts.

**Describe the solution you'd like**
Please add a GoogleAccount to the valid `type` for `octopusdeploy_variable` so that variables of Google Account may be created.

**Describe alternatives you've considered**
None that I'm aware.

**Additional context**
N/A

**Comment by jbristowe** [comment]
https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/variable

Docs have been updated. 👍

**Comment by twerthi** [comment]
Awesome, thank you!!
