### ISSUE TITLE
Support for space_id parameter on environment resource

### ISSUE THREAD

**Issue by mstrauch19** [OctopusDeployLabs/terraform-provider-octopusdeploy#380]
**Is your feature request related to a problem? Please describe.**
Because support for spaces depends on the provider used, it cannot be easily used in loops because of Terraform issues with loops and providers (such as [this one](https://github.com/hashicorp/terraform/issues/19932)).

It would be much easier to use in a loop over spaces if `space_id` was supported as a parameter for an environment like it is for almost every other OctopusDeploy resource. As is, it is frustrating to need to try and configure an entirely different strategy for this one resource than the others.

This relates to the issue https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/121 where this was requested, but the asker was satisfied with the provider functionality. The difference here is that that functionality does not work well in loops.

**Describe the solution you'd like**
I would like `space_id` to be added as a supported parameter for `octopusdeploy_environment` resources as it is in most other resources so it does not depend on the provider setup.

**Describe alternatives you've considered**
This will work without loops, because it is the Terraform provider loop issues that cause the problem. But that requires a lot more manual definition in your HCL.

It could potentially work to define a small set of spaces as data and pass them around to every module, however this requires provider definitions for each space in every module, and makes changes difficult.

**Additional context**
TF version - 1.1.6
OctopusDeploy provider version - 0.7.69

**Comment by domenicsim1** [comment]
Supported in v0.13 of terraform provider.
Added in #558
