### ISSUE TITLE
Documentation - Multiple Space Aliases - Error Extraneous Label for Provider

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeployLabs/terraform-provider-octopusdeploy#381]
**Describe the bug**
When configuring multiple Spaces using Provider Aliases via the documentation on the Octopus Provider page, an error is received saying Providers are only able to have one label.

This only effects the 'unscoped' Provider

**Steps to reproduce**
Follow suggested process outlined in the [Octopus Provider Documentation](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs#multiple-spaces)

Use the following Provider:
```
provider "octopusdeploy" "unscoped" {
  address = "https://octopus.example.com"
  api_key = "API-XXXXXXXXXXXXX"
}
```

**Logs and other supporting information**
```
  $ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Extraneous label for provider
│
│ On main.tf line 10: Only 1 labels (name) are expected for provider blocks.
```

**Screenshots**
<img width="747" alt="Screen Shot 2022-05-19 at 11 31 11" src="https://user-images.githubusercontent.com/78527975/169183976-824428c1-e276-4812-b103-0e3f9cd5a7e5.png">

**Environment and versions:**
```
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/octopusdeploylabs/octopusdeploy v0.7.70
```

**Additional context**
Just requires changing the unscoped alias to not have a second label:
```
# Unscoped Provider
provider "octopusdeploy" {
  address = "https://<OCTOURL>"
  api_key = "API-XXXXX"
}
```

**Comment by zentron** [comment]
Duplicate https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/555
