### ISSUE TITLE
GetByID: input parameter (id) is invalid - octopusdeploy_nuget_feed resource

### ISSUE THREAD

**Issue by kengibous** [OctopusDeployLabs/terraform-provider-octopusdeploy#384]
**Describe the bug**
Attempting to create an octopusdeploy_nuget_feed resources results in the following error

`
Error: GetByID: the input parameter (id) is invalid
`

**Steps to reproduce**
Define a resource such as

```
resource "octopusdeploy_nuget_feed" "test" {
  download_attempts              = 1
  download_retry_backoff_seconds = 30
  feed_uri                       = "https://api.nuget.org/v3/index.json"
  is_enhanced_mode               = true
  password                       = "test-password"
  name                           = "Test NuGet Feed (OK to Delete)"
  username                       = "test-username"
}
```
run commands -

`terraform plan`
`terraform apply`

The apply will result in the error, but creates the feed in octopus - however it is not tracked in terraform state.

**Expected behavior**
Create the feed resource correctly and not report a `GetByID: the input parameter (id) is invalid` error

**Logs and other supporting information**
terraform `apply` logs

```
2022-05-20T08:03:18.598-0700 [INFO]  Terraform version: 1.1.9
2022-05-20T08:03:18.598-0700 [INFO]  Go runtime version: go1.17.2
2022-05-20T08:03:19.644-0700 [DEBUG] Resource state not found for node "octopusdeploy_nuget_feed.test", instance octopusdeploy_nuget_feed.test
2022-05-20T08:03:19.644-0700 [DEBUG] ProviderTransformer: "octopusdeploy_nuget_feed.test" (*terraform.NodeApplyableResourceInstance) needs provider["registry.terraform.io/octopusdeploylabs/octopusdeploy"]
2022-05-20T08:03:19.807-0700 [DEBUG] ReferenceTransformer: "octopusdeploy_nuget_feed.test" references: []
2022-05-20T08:03:20.852-0700 [DEBUG] octopusdeploy_nuget_feed.test: applying the planned Create change
2022-05-20T08:03:21.443-0700 [ERROR] vertex "octopusdeploy_nuget_feed.test" error: GetByID: the input parameter (id) is invalid
│ Error: GetByID: the input parameter (id) is invalid
│
│   with octopusdeploy_nuget_feed.test,
│   on feeds.tf line 15, in resource "octopusdeploy_nuget_feed" "test":
│   15: resource "octopusdeploy_nuget_feed" "test" {
```
**Environment and versions:**
- OS: `Microsoft Windows 10 Enterprise - 10.0.19044`
- Octopus Server Version: `2022.1.2592`
- Terraform Version: `1.1.9`
- Octopus Terraform Provider Version: `0.7.72`

**Additional context**

**Comment by kengibous** [comment]
FWIW - this works fine on 0.7.68,69 0.7.70, 0.7.71 but *not* 0.7.72

**Comment by cronjevh** [comment]
May be related .. I tried creating a docker cr feed with 
`resource "octopusdeploy_docker_container_registry" "dockerhub" {
  feed_uri = "https://index.docker.io"
  name     = "Dockerhub"
  space_id = "Spaces-1"
}`

and got error 
`│ Error: Provider produced inconsistent result after apply
│ When applying changes to octopusdeploy_docker_container_registry.dockerhub, provider "provider[\"registry.terraform.io/octopusdeploylabs/octopusdeploy\"]" produced an unexpected new value: Root resource was present, but now absent`

Changing Octopus Terraform Provider Version: 0.7.72 ->  0.7.71 Feed gets created as expected.

**Comment by jbristowe** [comment]
Thanks for submitting this issue. I can confirm that this issue is fixed in the next release. 😄
