### ISSUE TITLE
Release Workflow Should Re-Generate Docs

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeployLabs/terraform-provider-octopusdeploy#401]
**Is your feature request related to a problem? Please describe.**
Currently, documentation is generated through [terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs) and changes are pushed to the repo.

**Describe the solution you'd like**
The release workflow should be updated to re-generate the documentation and push changes to the repo.

**Comment by mjhilton** [comment]
We now have a [Validate Docs](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/actions/workflows/docs.yml) action which runs as a pre-merge check on PRs, to ensure that devs regen the docs before merging. This ensures it gets done, without causing system/bot commits to fill up history. I think the desired outcome of this issue has been achieved.
