### ISSUE TITLE
Octopus.ControlType Error with Octopus Deploy API Creating Octopus Variable

### ISSUE THREAD

**Issue by nbamrah** [OctopusDeployLabs/terraform-provider-octopusdeploy#409]
**Describe the bug**

Note: Using GitLab CICD

The issue occurs when using the octopus deploy provider and creating a variable resource, updating the resource, through the octopus deploy ui, to specify the control type and saving again. This causes a change to the variable resource to include "displaysettings" with the control type. The octopus deploy provider doesn't support displaysettings/control type for the variable resource, and the error is thrown by the octopus api specifying that "control type" has not been referenced in the variable resource. This issue is thrown in the octopus ui as well with the same error: **The given key 'Octopus.ControlType' was not present in the dictionary**

**Steps to reproduce**

1. Create a variable resource for a project in terraform and run terraform apply
2. Log into Octopus Deploy and manually update the newly created variable by clicking into your project and clicking on "Variables" on the left navigation
3. Click on the variable and open it in the editor and select "Prompt" and click the drop down for control type
4. Change control type to drop down and input a list of values
5. Click done and save the variable
6. Rerun the terraform apply (this results in the **The given key 'Octopus.ControlType' was not present in the dictionary** issue)
7. Go back into Octopus and uncheck "Prompt"
8. Click "Done" followed by "Save"
9. Rerun a terraform apply
10. This also results in the "Octopus.ControlType" error

**Expected behavior**

The expected behavior is to make a change to the variable (through the ui) and rerun the terraform apply on the resource. This requires to have the Terraform Octopus Provider to support "DisplaySettings"/"ControlType" for the variable resource.

**Logs and other supporting information**
Results of the terraform apply command:

│ Error: Octopus API error: The given key 'Octopus.ControlType' was not present in the dictionary. [] 
│ 
│   with octopusdeploy_variable.testvar,
│   on example.tf line 259, in resource "octopusdeploy_variable" "testvar":
│  259: resource "octopusdeploy_variable" "testvar" {

**Screenshots**

**Environment and versions:**
- OS: Linux
- Octopus Server Version: 2022.2 Build 5111
- Terraform Version: 1.1.9
- Octopus Terraform Provider Version: 0.7.71/0.7.73

**Additional context**

<img width="1693" alt="ManuallyUpdatedToDropDown" src="https://user-images.githubusercontent.com/38539918/172689544-d8dcebd2-5f83-4632-8886-27a216bf178a.png">
<img width="1692" alt="RemovedDropDown" src="https://user-images.githubusercontent.com/38539918/172689562-0b3917e1-2cc9-4d1a-95e2-72113e6c6044.png">

**Comment by nbamrah** [comment]
adding to the reproducible steps:

after manually updating the variable in the octopus ui, I tried adding a new variable resource to the project and then ran the terraform apply, encountering the error.

I also submitted a ticket to Octopus Support notifying them of the issue as well.

**Comment by jbristowe** [comment]
Thanks @nbamrah! I've logged a feature request for the Go API client, which is used by the Terraform Provider.

**Comment by millerjn21** [comment]
Source (INTERNAL): https://octopus.zendesk.com/agent/tickets/90603

**Comment by csyme-cmc** [comment]
> Thanks @nbamrah! I've logged a feature request for the Go API client, which is used by the Terraform Provider.

Hi @jbristowe 
Is there any update around the Go API client feature request?

**Comment by slewis74** [comment]
I did some investigation on this yesterday and wasn't able to reproduce it on the current versions of Octopus and the Octopus Terraform Provider. I did find that prompted variable support wasn't implemented correctly though, so #470 is on its way to address that.

**Comment by slewis74** [comment]
That PR has merged and as part of `v0.10.0`.
