### ISSUE TITLE
Setting a condition_expression with Variable condition on a step results in an error

### ISSUE THREAD

**Issue by ts-cbuehrle** [OctopusDeployLabs/terraform-provider-octopusdeploy#410]
I'm trying to setup a variable run condition using the Terraform Provider and get the following error on the project. If I use a `Success` or `Always` condition then the step is created. I tried other `condition_expression` but it seems like it's not getting set at all.

```
step {
  condition             = "Variable"
  condition_expression  = "1"
  name                  = "Run E2E Tests"
  package_requirement.  = "LetOctopusDecide"
  start_trigger         = "StartAfterPrevious"

  action {
    action_type   = "Octopus.Script"
    disabled      = contains(lookup(var.projects_details[each.key], "disabledSteps", []), "Run E2E Tests")
    name          = "Run E2E Tests"
    required      = false
    run_on_server = true
....
```

**Expected behavior**
The step is created with a variable condition specified in the condition_expression.

**Logs and other supporting information**
Output on the terraform apply:

```
Error: octopus deploy api returned an error on endpoint /api/Spaces-846/deploymentprocesses/deploymentprocess-Projects-7593 - [Please add a variable expression for your variable run condition.]
```

**Screenshots**

**Environment and versions:**
- OS: OSX
- Octopus Server Version: 2021.3.8275
- Terraform Version: 0.12.28
- Octopus Terraform Provider Version: 0.7.7

**Comment by zentron** [comment]
This issue is no longer reproducable.
