### ISSUE TITLE
Canonical Tag Name is Not Optional on Tag Resources

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeployLabs/terraform-provider-octopusdeploy#432]
The attribute, `canonical_tag_name` is currently marked as both `Computed` and `Optional` on the `tag` resource. This is not correct; this attribute should ONLY be marked as `Computed`. Users should NOT be able to set this attribute. It is auto-generated by Octopus Deploy.

**Comment by slewis74** [comment]
From further discussions, this property is actually of no value to the Terraform provider. It is a readonly value emited from Octopus server and has no inherent value when specifying a configuration.
We'll look at a schema change to remove the property altogether.

**Comment by jbristowe** [comment]
Update: After a review of this issue, it has been decided that the `canonical_tag_name` will remain in the `tag` resource as it is required for tenant tags:

```hcl
resource "octopusdeploy_tenant" "test-tenant-resource" {
  name = "test-tenant-name"
  tenant_tags = [
    octopusdeploy_tag.test-tag-a.canonical_tag_name,
    octopusdeploy_tag.test-tag-b.canonical_tag_name
  ]
}
```

Note: `octopusdeploy_tag` will become a root-level resource once #433 is closed.
