### ISSUE TITLE
Reordering of tags withing a tag set breaks the tag Ids in Octopus

### ISSUE THREAD

**Issue by slewis74** [OctopusDeployLabs/terraform-provider-octopusdeploy#433]
**Describe the bug**
The Terraform provider currently models TagSets in a way that closely mimicks the Octopus server API. Unfortunately this leads to some issues because internally Octopus actually treats the tag objects as though they were aggregates, and their Ids are really important to other things like TenantTags, which reference the tags directly.

To put this another way, the physical model server and its API has for TagSets look like an aggregate root that contains Tags, but conceptually that is not how it uses them. Conceptually there are tag aggregates that are grouped together by a tag set name.

This has implication to Terraform, which is using positional based indexing to align the configuration file with its state. Thus changes in order to the tags result in breaking changes, because it renames existing Ids and therefore changes the meaning of all references to the current tags.

**Steps to reproduce**
To see the issue apply a configuration something like the following

```
resource "octopusdeploy_tag_set" "tagSet_region" {
  name             = "region"
  description      = ""
 
  tag {
      name  = "us-east"
      color = "#FF0000"
  }
  tag {
      name  = "us-west"
      color = "#00FF00"
  }
}
```
Now modify the configuration to include this tag between the existing tags and do a plan
```
  tag {
      name  = "us-central"
      color = "#0000ff"
  }
```
the result will look something like this
![image](https://user-images.githubusercontent.com/4229735/181430203-c716cd6d-dd27-451a-b3cc-bc0a1e8cfc32.png)
where the existing entry is renamed and a new entry with the existing name is assumed to be created.
(this example only shows a single tag after the inserted one. If there are multiple after the inserted one then they will all get renamed).

**Expected behavior**
The provider should not get confused by entries changing order.

**Environment and versions:**
- Octopus Terraform Provider Version: `0.7.73`

**Comment by jbristowe** [comment]
A resolution to this issue is to promote `tag` resources to the root level and associate them with `tag_set` resources through an attribute:

```hcl
resource "octopusdeploy_tag_set" "north-america" {
  description = "Tenants for the North American region"
  name        = "North America"
}

resource "octopusdeploy_tag" "us-west" {
  color   = "#0000ff"
  name    = "us-west"
  tag_set = octopusdeploy_tag_set.tag-set-region.id
}

resource "octopusdeploy_tag" "us-east" {
  color   = "#00ff00"
  name    = "us-east"
  tag_set = octopusdeploy_tag_set.tag-set-region.id
}
```

**Comment by slewis74** [comment]
just to be clear ☝️ is how we think we'll change the provider implementation to get around this issue. In short, it would be an inversion of the way the data is managed from the provider's perspective. We're working through how this would work and how migration etc from current to this model would look/work.

**Comment by jbristowe** [comment]
**Workaround:**

If you are managing tags in a `tag_set` resource, you must preserve the `tag` list order. This means that `tag` blocks must be appended in a top-down fashion; new `tag` blocks must be added to the bottom of the a `tag_set` resource. It is also recommended that you do not manage the configuration of `tag_set` resource inside the context of a `for` expression as order cannot be guaranteed.

**Comment by jbristowe** [comment]
Update: We will publishing a new version that will resolve this behaviour. This version will constitute a breaking change. It is impossible for us to provide a schema migration for this change.

**Comment by jbristowe** [comment]
An example using the new implementation in `v0.8.0` in a `for` expression will resemble the following:

```hcl
locals {
  tagSets = [
    { name : "Regions", description : "Geographic Regions", tag : [{ name : "us-east", color : "#FF0000" }, { name : "us-east-dev", color : "#FF0000" }, { name : "us-east-test", color : "#FF0000" }] },
    { name : "Retailers", description : "Retailers", tag : [{ name : "Men's Clothing", color : "#0000FF" }, { name : "Women's Clothing", color : "#FF0000" }] }
  ]
}

resource "octopusdeploy_tag_set" "tagset" {
  for_each    = { for tagSet in local.tagSets : tagSet.name => tagSet }
  name        = each.value.name
  description = each.value.description
}

locals {
  tags = flatten([
    for tagset_key, tagset in local.tagSets : [
      for tag_key, tag in tagset.tag : {
        tag_set_id = octopusdeploy_tag_set.tagset[tagset.name].id
        name       = tag.name
        color      = tag.color
      }
    ]
  ])
}

resource "octopusdeploy_tag" "tag" {
  for_each   = { for tag in local.tags : tag.name => tag }
  name       = each.value.name
  color      = each.value.color
  tag_set_id = each.value.tag_set_id
}
```
