### ISSUE TITLE
Add support for Git Credentials in project version control

### ISSUE THREAD

**Issue by martinisaksen** [OctopusDeployLabs/terraform-provider-octopusdeploy#448]
**Is your feature request related to a problem? Please describe.**
We are using the username and password created in Library -> Git Credentials for our Config-as-Code. There is no option in terraform to reference these credentials and so all of our projects currently set up with version control can no longer be managed via terraform. The terraform deployment will fail because no credentials are provided for git.

**Describe the solution you'd like**
Add the ability to specify Git Credentials in the `git_persistence_settings.credentials` property in the project resource.

**Comment by martinisaksen** [comment]
Seeking feedback on how to implement this in the project schema.

Currently the project schema is only set up to work with username and password for authenticating to the Git repo. The `credentials` section only allows `username` and `password`. They are both required. I have come up with two options for supporting the use of Git Credentials stored in the Library:

1. Make `username` and `password` optional but conflicting with a new property `library` that stores the referenced Git Credential Id. This would make it backwards compatible but open up the possibility for someone to provide only `username` or `password` and not both, This would cause them to not get a warning but fail in  `apply`.
```terraform
"credentials": {
	Description: "The authentication option associated with these version control settings.",
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"library": {
				ConflictsWith: []string{"username", "password"},
				Description:   "The Git credential ID to use from the Library.",
				Optional:      true,
				Type:          schema.TypeString,
			},
			"password": {
				ConflictsWith: []string{"library"},
				Description:      "The password for the Git credential.",
				Optional:         true,
				Sensitive:        true,
				Type:             schema.TypeString,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringIsNotEmpty),
			},
			"username": {
				ConflictsWith: []string{"library"},
				Description:      "The username for the Git credential.",
				Optional:         true,
				Type:             schema.TypeString,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringIsNotWhiteSpace),
			},
		},
	},
	MaxItems: 1,
	Optional: true,
	Type:     schema.TypeList,
},
```
2. Wrap the `username` and `password` with a `basic` parent node. This would allow both properties to stay required, but make `basic` optional. This would break existing setups because of schema change, but would make it easier to add additional auth options in the future, like SSH.
```terraform
"credentials": {
	Description: "The authentication option associated with these version control settings.",
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"library": {
				ConflictsWith: []string{"basic"},
				Description:   "The Git credential ID to use from the Library.",
				Required:      true,
				Type:          schema.TypeString,
			},
			"basic": {
				ConflictsWith: []string{"library"},
				Description:   "The credentials associated with these version control settings.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"password": {
							Description:      "The password for the Git credential.",
							Required:         true,
							Sensitive:        true,
							Type:             schema.TypeString,
							ValidateDiagFunc: validation.ToDiagFunc(validation.StringIsNotEmpty),
						},
						"username": {
							Description:      "The username for the Git credential.",
							Required:         true,
							Type:             schema.TypeString,
							ValidateDiagFunc: validation.ToDiagFunc(validation.StringIsNotWhiteSpace),
						},
					},
				},
				MaxItems: 1,
				Optional: true,
				Type:     schema.TypeList,
			},
		},
	},
	MaxItems: 1,
	Optional: true,
	Type:     schema.TypeList,
},
```

Please let me know what your thoughts are on the proposed solutions.

**Comment by martinisaksen** [comment]
@jbristowe Is there anyone I can work with to settle on how to structure the addition of Library Git Credentials to projects?

**Comment by ann-mwangi** [comment]
We have added this support in our [latest release](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/releases/tag/v0.9.1). Please check it out.

**Comment by jbristowe** [comment]
Closing this issue; support for credentials was added in v0.9.1. 👍
