### ISSUE TITLE
Ability to reference OCL files directly from TF Provider

### ISSUE THREAD

**Issue by shipra-octopus** [OctopusDeployLabs/terraform-provider-octopusdeploy#455]
**Is your feature request related to a problem? Please describe.**
When using TF provider to create or edit projects within Octopus, it would be great to point directly to the relevant OCL code for the Process and the Variables.

**Describe the solution you'd like**
Add an option to point to process.ocl and variables.ocl files when describing project state in TF Provider. Example -

```
resource "octopusdeploy_deployment_process" "deployment" {
  ocl = file("deployment-process.ocl")
}
```

**Comment by zentron** [comment]
After some further discussions we have decided that we are unlikely to currently go with this approach unless other requirements create the demand.
[Internal Link](https://docs.google.com/document/d/13t6_Cca-wCB58Gy0EEa_j1v0dXT4_jOLJuWN0XaPU_0/edit#heading=h.ca33now8o3m7)
