### ISSUE TITLE
Add Git credential as a data source

### ISSUE THREAD

**Issue by ann-mwangi** [OctopusDeployLabs/terraform-provider-octopusdeploy#459]
**Describe the bug**
In the Terraform Version 0.9.0, there is support for Git credentials. However, one issue is that the credential has not been added as a data source. This is important as customers want to keep the code clean from passwords.

**Expected behavior**
`data "octopusdeploy_git_credential" "bitbucket" {
 name = "bitbucket"
}`

**Error log**
`Error: Invalid data source
November 8th 2022 18:47:01
Error
on data.tf line 57, in data "octopusdeploy_git_credential" "bitbucket":
November 8th 2022 18:47:01
Error
57: data "octopusdeploy_git_credential" "bitbucket" {
November 8th 2022 18:47:01
Error
The provider octopusdeploylabs/octopusdeploy does not support data source
November 8th 2022 18:47:01
Error
"octopusdeploy_git_credential".
November 8th 2022 18:47:01
Error
Did you intend to use the managed resource type
November 8th 2022 18:47:01
Error
"octopusdeploy_git_credential"? If so, declare this using a "resource" block
November 8th 2022 18:47:01
Error
instead of a "data" block.
November 8th 2022 18:47:01
Error
[41mError on or near line 352: Error running terraform plan; exiting with status 1[0m`

**Environment and versions:**
- Terraform Version: `0.9.0`

**Comment by Clare-Octopus** [comment]
User here (Internal) is the one to discover this issue - https://octopus.zendesk.com/agent/tickets/97679 

As a workaround he was able to hardcode the value:

` git_credential_id = "GitCredentials-1"`
