### ISSUE TITLE
The TF plan displays the removal of all users from the team instead of adding a new one

### ISSUE THREAD

**Issue by TaigaMoose** [OctopusDeployLabs/terraform-provider-octopusdeploy#465]
**Describe the bug**
When I create a new user and add him to the existing team with `octopusdeploy_team` resource, the TF plan displays the removal of all users from the team instead of adding a new one.

**Steps to reproduce**
1. Add new user from `module.common.users` structure:
```
resource "octopusdeploy_user" "users" {
  for_each      = module.common.users
  display_name  = each.value.user_displayname
  email_address = each.value.email
  password      = random_password.password.result # get from secure environment/store
  username      = each.value.email
  is_active     = true
  identity {
    provider = "Google Apps"
    claim {
      name                 = "dn"
      is_identifying_claim = "0"
      value                = each.value.user_displayname
    }
    claim {
      name                 = "email"
      is_identifying_claim = "1"
      value                = each.value.email
    }
  }
}
```
3. Add new user to existing team:
```
resource "octopusdeploy_team" "teams" {
  for_each = local.teams
  name     = each.value.name
  users = [
    for user, props in each.value.users : octopusdeploy_user.users["${user}"].id
  ]
}
```

**Expected behavior**
Like this:
```
# octopusdeploy_team.teams["DevF"] will be updated in-place
  ~ resource "octopusdeploy_team" "teams" {
        id                 = "Teams-361"
        name               = "DevF"
      ~ users              = [
          + (known after apply),
            # (1 unchanged element hidden)
        ]
        # (4 unchanged attributes hidden)
    }
```

**Logs and other supporting information**
TF plan for adding new user to the group:
```
Terraform will perform the following actions:

  # octopusdeploy_team.teams["Helpdesk"] will be updated in-place

  ~ resource "octopusdeploy_team" "teams" {
        id                 = "Teams-343"
        name               = "Helpdesk"
      ~ users              = [
          - "Users-1310",
          - "Users-1330",
          - "Users-1466",
          - "Users-1472",
          - "Users-1474",
          - "Users-1541",
          - "Users-762",
        ] -> (known after apply)
        # (4 unchanged attributes hidden)
    }
```
TF output with the list of users that is passed to `octopusdeploy_team` resource:
```
Changes to Outputs:
  + name = [
      + "Users-1472",
      + "Users-1474",
      + "Users-1330",
      + "Users-762",
      + "Users-1466",
      + "Users-1310",
      + (known after apply),
      + "Users-1541",
    ]
```

**Screenshots**

**Environment and versions:**
- OS: Ubuntu Linux container on GitHub actions
- Octopus Server Version: v2022.2 (build 7457)
- Terraform Version: 1.1.0-1.1.8
- Octopus Terraform Provider Version: 0.9.2

**Additional context**

**Comment by jbristowe** [comment]
Hey @TaigaMoose! :wave: I can confirm that this is (indeed) the behaviour associated with this operation. However, the Terraform plan that's generated does not reflect the changes that would change if you were to apply them. I'm not sure why the CLI displays the plan in this manner. If you add a new user ID to a team and apply this change, the team that's reflected in your state/configuration will be the one that's propagated to Octopus Deploy.

I would be happy to re-open this issue if you think I'm missing something here.

**Comment by TaigaMoose** [comment]
Could you change the behavior in the future versions of the provider so that it displays a more understandable plan of TF apply?
Probably like this:
```
# octopusdeploy_team.teams["DevF"] will be updated in-place
  ~ resource "octopusdeploy_team" "teams" {
        id                 = "Teams-361"
        name               = "DevF"
      ~ users              = [
          + (known after apply),
            # (1 unchanged element hidden)
        ]
        # (4 unchanged attributes hidden)
    }
```

**Comment by TaigaMoose** [comment]
@jbristowe
One more question: could you recommend a variant of code which we can use for more correct TF plan?
