### ISSUE TITLE
Unable to update credentials for octopusdeploy_aws_elastic_container_registry due to plugin crash (0.9.4)

### ISSUE THREAD

**Issue by Shanjohn** [OctopusDeployLabs/terraform-provider-octopusdeploy#469]
**Describe the bug**
After a AWS access key change octopusdeploy_aws_elastic_container_registry resource cannot be updated due to a plugin crash. Appeared in provider version 0.9.4, everything is fine on 0.9.3

**Steps to reproduce**
1. Create two AWS access keys and octopusdeploy_aws_elastic_container_registry by referencing a first key, apply changes.
2. Change the key reference to the second key, apply changes.
4. See error:

`panic: interface conversion: feeds.IFeed is *feeds.AwsElasticContainerRegistry, not *feeds.FeedResource

goroutine 68 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceAwsElasticContainerRegistryUpdate({0x1a52408, 0xc00058cd80}, 0xc0006c7780, {0x17de820?, 0xc000136840})
        github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy/resource_aws_elastic_container_registry.go:102 +0x3a8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000670000, {0x1a52440, 0xc000781200}, 0xd?, {0x17de820, 0xc000136840})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000670000, {0x1a52440, 0xc000781200}, 0xc000046ea0, 0xc0006c7580, {0x17de820, 0xc000136840})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000310570, {0x1a52440?, 0xc0007810e0?}, 0xc000634d20)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000e60a0, {0x1a52440?, 0xc0006c52f0?}, 0xc0003b3a40)
        github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1890ce0?, 0xc0000e60a0}, {0x1a52440, 0xc0006c52f0}, 0xc0003b39d0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000206000, {0x1a575c0, 0xc00050d860}, 0xc000704240, 0xc000774120, 0x2046dc0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000206000, {0x1a575c0, 0xc00050d860}, 0xc000704240, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-octopusdeploy_v0.9.4.exe plugin crashed!`

**Expected behavior**
I expect octopusdeploy_aws_elastic_container_registry to be updated without errors when the key changes.

**Logs and other supporting information**
Add the output of running `tf plan` or `tf apply` along with any errors in the Octopus Server logs.

**Environment and versions:**
- OS: [`Windows`, `Linux`] (Can't test on OS X)
- Octopus Server Version: [e.g. `2022.3.10437`]
- Terraform Version: [`1.3.2`]
- Octopus Terraform Provider Version: [`0.9.4`]

**Comment by jbristowe** [comment]
Hey @Shanjohn! :wave: Apologies for this. This will be fixed in the next release.
