### ISSUE TITLE
Initial commit branch isn't being passed correctly in some case

### ISSUE THREAD

**Issue by slewis74** [OctopusDeployLabs/terraform-provider-octopusdeploy#477]
**Describe the bug**
During project conversion to being version controlled the Terraform provider is incorrectly passing the default initial commit branch to Octopus in all cases. It should only pass this value when the default branch is protected. In all other cases, the default branch will be what server uses to do the conversion.

**Steps to reproduce**
1. Create a project
2. Convert it to VCS, with no protected branches.
3. Open the project in the portal. The page will render an error along the lines of `Repository not initialized`.
4. Confirm that server has created a branch called `octopus-vcs-conversion`

**Expected behavior**
The portal should not get an error. It should open the default branch and that's where the conversion should have happened.

**Screenshots**
See https://octopus.zendesk.com/agent/tickets/105325

**Environment and versions:**
- OS: all
- Octopus Server Version: 2022.4
- Terraform Version: n/a
- Octopus Terraform Provider Version: `0.10.1`

**Comment by Clare-Octopus** [comment]
Another customer affected (internal ticket) - https://octopus.zendesk.com/agent/tickets/105371
