### ISSUE TITLE
New Tenant is broken

### ISSUE THREAD

**Issue by JustinPullen** [OctopusDeployLabs/terraform-provider-octopusdeploy#487]
**Describe the bug**
When creating a new tenant against octopus version 2023.1.8841-hotfix.9519 One will receive the below error.

[The TenantTags field is required. The ProjectEnvironments field is required.]

**Steps to reproduce**
- Use the Code below to replicate the issue. 

resource "octopusdeploy_tenant" "tenant" {
  name     = "tenant1"
}

- Terraform apply 

- Observe the Error on the Command Line
[The TenantTags field is required. The ProjectEnvironments field is required.]

**Expected behavior**
No error would be thrown and tenant would be created

**Environment and versions:**
- OS: [`Linux`, `OSX`]
- Octopus Server Version: [`2023.1.8841-hotfix.9519`]
- Terraform Version: [`v1.3.9`]
- Octopus Terraform Provider Version: [`0.10.0+`]

**Comment by andrewabest** [comment]
Thanks for the report @JustinPullen!

We are in the middle of an API migration, and it looks like you've caught a regression. We are shipping a fix for this ASAP, you should be able to track progress on https://github.com/OctopusDeploy/Issues/issues/8057.

**Comment by JustinPullen** [comment]
Fixed in Release 2023.1.9602
