### ISSUE TITLE
Update action on space resource fails with: The TaskQueueStopped field is required.

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeployLabs/terraform-provider-octopusdeploy#494]
**Describe the bug**
When attempting to update an existing space resource, the following error is displayed: `The TaskQueueStopped field is required.`

Destroying and Creating works fine, but updating existing always expects the TaskQueueStopped value.

**Steps to reproduce**
Terraform I used for a simple reproduction.

``` terraform
terraform {
  required_providers {
    octopusdeploy = {
      source  = "OctopusDeployLabs/octopusdeploy"
      version = ">= 0.10.5"
    }
  }
}

provider "octopusdeploy" {
  address = var.serverURL
  api_key = var.apiKey
}

resource "octopusdeploy_space" "example" {
  description           = var.description
  name                  = var.octopus_space_name
  is_default            = var.is_default
  is_task_queue_stopped = false
  space_managers_teams  = ["teams-everyone", "teams-managers"]
}
```
1. Create Space resource with the above.
2. Change the team assignment under `space_managers_teams` (I removed `"teams-everyone", `)
3. `terraform apply` will attempt to update the existing space resource and should give the below output/error.

**Logs and other supporting information**
``` terraform
octopusdeploy_space.example: Creation complete after 2s [id=Spaces-843]
  # octopusdeploy_space.example will be updated in-place
  ~ resource "octopusdeploy_space" "example" {
        id                          = "Spaces-843"
        name                        = "DanielTestSpace"
      ~ space_managers_teams        = [
          - "teams-everyone",
            "teams-managers",
        ]
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
octopusdeploy_space.example: Modifying... [id=Spaces-843]
╷
│ Error: octopus deploy api returned an error on endpoint /api/spaces/Spaces-843 - [The TaskQueueStopped field is required.]
│
│   with octopusdeploy_space.example,
│   on main.tf line 23, in resource "octopusdeploy_space" "example":
│   23: resource "octopusdeploy_space" "example" {
│
╵
```

**Environment and versions:**
- Octopus Server Version: [e.g. `2023.2 (Build 1191-hotfix.1386)`]
- Terraform Version: [e.g. `1.2.4`]
- Octopus Terraform Provider Version: [e.g. `0.10.5`]

**Additional context**
Internal Source: https://octopus.zendesk.com/agent/tickets/109600

**Comment by johnsimons** [comment]
Fixed in v0.11.0
