### ISSUE TITLE
Mistake in docs in example for octopusdeploy_variable 

### ISSUE THREAD

**Issue by ArturDorochowicz** [OctopusDeployLabs/terraform-provider-octopusdeploy#505]
**Describe the bug**
The example in the docs for octopusdeploy_variable has this fragment:
```terraform
# create an Azure service principal account variable
resource "octopusdeploy_account" "azure_service_principal_account_variable" {
  owner_id  = "Projects-123"
  type      = "AzureAccount"
  name      = "My Azure Service Principal Account (OK to Delete)"
  value     = "Accounts-123"
}
```

Should it rather start with `resource "octopusdeploy_variable" ...`?

**Comment by zentron** [comment]
Thanks @ArturDorochowicz .
Fixed by https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/commit/2bd5476f711b3d769bf9395e374fa42b6aa64242
