### ISSUE TITLE
Creating multiple version controlled projects has issues with protected branches even when the target repository has none

### ISSUE THREAD

**Issue by danielfischeroctopus** [OctopusDeployLabs/terraform-provider-octopusdeploy#508]
**Describe the bug**

Protected branches are an ongoing problem with our provider. When creating a new VCS project through Terraform, a pull request is made under the branch `octopus-vcs-conversion`. So when creating multiple VCS projects for the same repository and under different subdirectories, we fail after the first project as they all attempt to use the same branch name.

This happens even if you're creating the project in a repository without protected branches.

**Steps to reproduce**

1. Use Terraform to create multiple version controlled projects in the same repository with different subdirectory. (`.\Octopus\Project-1` & `.\Octopus\Project-2`)
2. Whether you have a protected branch or not, the provider will create a new branch `octopus-vcs-conversion` for the first project it creates then fail on any subsequent projects as it attempts to create another branch of the same name to commit each project.

**Logs and other supporting information**
[Internal Source.](https://octopus.zendesk.com/agent/tickets/113588)
[Internal Conversation with example script for reproduction](https://octopusdeploy.slack.com/archives/C03SG0LFJHX/p1680067608152289).

**Environment and versions:**
- Terraform Version: [e.g. `1.2.4`]
- Octopus Terraform Provider Version: [e.g. `0.11.1`]

**Comment by zentron** [comment]
Resolved by https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/513
