### ISSUE TITLE
octopusdeploy_variable: always updates

### ISSUE THREAD

**Issue by mac2000** [OctopusDeployLabs/terraform-provider-octopusdeploy#514]
```tf
resource "azuread_application_password" "example" {
  application_object_id = azuread_application.example.object_id
}

resource "octopusdeploy_variable" "example" {
  name         = "example"
  value        = azuread_application_password.example.value
  type         = "Sensitive"
  is_sensitive = true
  owner_id     = "Projects-123"
}
```

Now each time plan shows something like

```log
 ~ resource "octopusdeploy_variable" "example" {
        name         = "example"
      + value        = (sensitive value)
        # (4 unchanged attributes hidden)
    }
```

I have tried `terraform state pull` to see what's inside, and indeed value in state is empty, that's why terraform will always try to update it

From one side we can not receive an secret value from Octopus api but shouldn't we somehow track it via hashed value or something like this

Unfortunately I'm not sure from where to start looking at [setVariable](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/main/octopusdeploy/schema_variable.go#L184) function and I just not see where it sets encrypted value, the same is true for [resource_variable](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/main/octopusdeploy/resource_variable.go)

Wondering if we can bypass and/or fix it with some small addition

**Comment by eternalapprentice2000** [comment]
this is not a bug, when putting data into the `octopusdeploy_variable` resource, you need to use the `sensitive_value` object

```
resource "octopusdeploy_variable" "example" {
  name         = "example"
  sensitive_value = azuread_application_password.example.value
  type         = "Sensitive"
  is_sensitive = true
  owner_id     = "Projects-123"
}
```

should resolve your issue

**Comment by mac2000** [comment]
hm, interesting, can not believe i have missed it, need check it

**Comment by mac2000** [comment]
Finally had a chance to test it and can confirm [solution](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/514#issuecomment-1777321226) definitely works!

Not sure if thats ok, closing this one, hopefully in future if someone will find it - just make sure to change not only variable type but set sensitive value instead of value

Thank for great product/project and provider :)
