### ISSUE TITLE
Project resources should allow omission of a service now integration standard change template name

### ISSUE THREAD

**Issue by amonicasei** [OctopusDeployLabs/terraform-provider-octopusdeploy#526]
**Is your feature request related to a problem? Please describe.**
When creating projects with the `octopusdeploy_project` resource, you may not define an empty `standard_change_template_name` in the project's `servicenow_extension_settings`. You can omit this property in the UI, but not via Terraform. Standard change templates introduce additional complexity to our Service Now workflow which is prohibitive for our use case.

**Describe the solution you'd like**
The ability to omit or leave blank the `octopusdeploy_project.servicenow_extension_settings.standard_change_template_name` property in Terraform configuration. If omitted, the Service Now integration should behave as it does if you omit the Standard Change Template name in the UI - it should not use a Standard Change Template when creating Change Requests.

**Describe alternatives you've considered**
The first alternative is to setup projects' Service Now integrations in the UI. This is not realistic because configuration changes to Octopus done via Terraform (which happen daily) would wipe out our manual changes in the UI.

The second alternative is to use Standard change templates. This is unrealistic for our use case due to the complexity it introduces into our custom flow. We originally tried to use Standard change templates and had to abandon them due to issues they introduced into our process.

**Additional context**
The provider documentation states this field is optional, yet it fails if you omit the property or set it to and empty string or a whitespace character.

Octopus Terraform Provider Version: [v0.12.3]

**Comment by zentron** [comment]
Fixed by https://github.com/OctopusDeploy/OctopusDeploy/pull/21308
