### ISSUE TITLE
Tenant & Tenant Tags - Unable To Be Created/Destroyed When Defined In Same File

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeployLabs/terraform-provider-octopusdeploy#540]
**Describe the bug**
When configuring Tenant and Tenant Tag Resources in the same file, the file that created the resources is unable to be used with a `terraform destroy` command and needs to be modified to delete the created resources.

**Steps to reproduce**
1. Create a Tenant and Tenant Tag resource in the same file:
```
resource "octopusdeploy_tag_set" "example" {
  description = "Provides tenants with access to certain early access programs."
  name        = "eap"
}

resource "octopusdeploy_tag" "alpha" {
  color      = "#00FF00"
  name       = "alpha"
  tag_set_id = octopusdeploy_tag_set.example.id
}

resource "octopusdeploy_tenant" "tenant1" {
		name = "tenant1-tf"
    tenant_tags = ["eap/alpha"]
		project_environment {
			project_id   = "Projects-1"
			environments = ["Environments-1"]
		}
}
```
2. Run `terraform destroy` without making any changes
3. See error - `tag in use`

**Expected behavior**
I expect the same file to be able to create and destroy resources

**Logs and other supporting information**
```
 Error: the tag may not be deleted; it is being used by one or more tenant(s)
```

**Environment and versions:**
- OS: Windows
- Octopus Server Version: [e.g. `2019.6.1`]
- Terraform Version: 1.3.6
- Octopus Terraform Provider Version: 0.12.6

**Additional context**
Tenants require tag_sets to exist prior however the opposite is true when being deleted which is similar to https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/539 however it looks to be a dependency the Tenant and Tag_set resources have rather than just the order they are created in the terraform file

**Comment by domenicsim1** [comment]
This is no longer an issue from v0.22.0
