### ISSUE TITLE
duplicate entries on each reapply

### ISSUE THREAD

**Issue by cloudlady911** [OctopusDeployLabs/terraform-provider-octopusdeploy#571]
**Describe the bug**
I am trying to create variables in my Octo projects

**Steps to reproduce**
1. Create definition in octopus.tf
```hcl
## efs sg to PSR IAC Project
resource "octopusdeploy_variable" "efs-sg" {
  owner_id  = "Projects-383"
  type      = "String"
  name      = "Project.EFS.SG"
  value     = aws_security_group.efs_access_sg.id
}
```
2. Apply
3. Project.EFS.SG exists with correct security group id
4. Reapply
5. Previously created variable now has two identical values
6. Reapply
7. Same variable now has 3 identical values

**Expected behavior**
the system should realize that this is an unchanged item and not modify it.

logs:
`# octopusdeploy_variable.vpc_id will be created 
November 2nd 2023 11:22:03Info
  + resource "octopusdeploy_variable" "vpc_id" { 
November 2nd 2023 11:22:03Info
      + encrypted_value = (known after apply) 
November 2nd 2023 11:22:03Info
      + id              = (known after apply) 
November 2nd 2023 11:22:03Info
      + is_editable     = true 
November 2nd 2023 11:22:03Info
      + is_sensitive    = false 
November 2nd 2023 11:22:03Info
      + key_fingerprint = (known after apply) 
November 2nd 2023 11:22:03Info
      + name            = "Project.VPC.ID" 
November 2nd 2023 11:22:03Info
      + owner_id        = "Projects-384" 
November 2nd 2023 11:22:03Info
      + space_id        = (known after apply) 
November 2nd 2023 11:22:03Info
      + type            = "String" 
November 2nd 2023 11:22:03Info
      + value           = "vpc-032fd1fb0f598ee71" 
November 2nd 2023 11:22:03Info
    } `

**Screenshots**
<img width="1044" alt="image" src="https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/assets/11928426/0ea50487-8765-45cc-99c3-42d972d23a08">

**Environment and versions:**
- OS: linux
- Octopus Server Version: 2023.2.12673
- Terraform Version: 1.6.2
- Octopus Terraform Provider Version: Terraform_Version=1.6.2

**Additional context**

**Comment by mjhilton** [comment]
Duplicates #212

There is more discussion and reproduction steps on the earlier issue #212, including [a workaround](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/212#issuecomment-1648306684) which might help.
