### ISSUE TITLE
Connectivity policy for octopusdeploy_project Resource not updating correctly - tfstate doesn't match Octopus Project

### ISSUE THREAD

**Issue by FinnianDempsey** [OctopusDeployLabs/terraform-provider-octopusdeploy#587]
**Describe the bug**
When updating the connectivity_policy for a Project Resource, the changes are being made in the tfstate file but not in the Octopus Project resource, specifically the `allow_deployments_to_no_targets` and `exclude_unhealthy_targets` values.

**Steps to reproduce**
1. Create a TF project with a connectivity_policy defined
2. Modify `allow_deployments_to_no_targets` or `exclude_unhealthy_targets`
3. Apply changes and see tfstate file updated
4. See values still used by Octopus Project via API

**Expected behavior**
Changes made in Terraform are reflected in Octopus

**Logs and other supporting information**
```
  # octopusdeploy_project.example will be updated in-place
  ~ resource "octopusdeploy_project" "example" {
        id                                   = "Projects-4648"
        name                                 = "TF Test Project"
        # (17 unchanged attributes hidden)

      ~ connectivity_policy {
          ~ allow_deployments_to_no_targets = true -> false
          ~ exclude_unhealthy_targets       = true -> false
```

**Environment and versions:**
- Octopus Server Version:  v1.6.5
- Terraform Version:  v1.6.5
- Octopus Terraform Provider Version: >=0.14.2

**Additional context**
[Internal Link - Zendesk](https://octopus.zendesk.com/agent/tickets/164374)

**Comment by mjhilton** [comment]
This looks to have been fixed since it was reported.

I'm able to apply ConnectivityPolicy blocks and change them across applies, and the settings persist both to `tfstate` and to Octopus Server.
