### ISSUE TITLE
Certificate does not update

### ISSUE THREAD

**Issue by Dusty-Meg** [OctopusDeployLabs/terraform-provider-octopusdeploy#598]
**Describe the bug**
Using the octopusdeploy_certificate resource the certificates are not being updated within Octopus.
The certificate is being renewed in Terraform, but the resource in Octopus is not changing.
I can see via the audit log that the DataVersion of the certificate is being updated within Octopus cloud but the actual certificate is not being replaced.

**Steps to reproduce**
1. Have a certificate renewed in Terraform
2. Terraform apply ran

**Expected behaviour**
Renew the lets encrypt certificate in Terraform and the certificate then updated in Octopus to be used by deployments.

**Environment and versions:**
- OS: Windows
- Octopus Server Version: Octopus cloud v2024.1 (Build 8396)
- Terraform Version: v1.7.0
- Octopus Terraform Provider Version: 0.14.5

**Additional context**
```terraform
resource "octopusdeploy_certificate" "site_one" {
  count            = var.environment != "prod" ? local.site_one_enabled : 0
  certificate_data = format("%s%s%s", module.site_one[0].private_key_pem, module.site_one[0].certificate_pem, module.site_one[0].issuer_pem)
  name             = local.site_one_ui_base_url
  environments     = var.octopus_environments
}

**Comment by Dusty-Meg** [comment]
Just a slight addition to this, it seems to not be updating anything. The name of the cert was updated in the terraform state but this was not reflected inside of Octopus

**Comment by zentron** [comment]
Thanks @Dusty-Meg , I've added this item to our backlog to investigate

**Comment by EduardoSantanaSeverino** [comment]
I have same issue. the certificate was updated in terraform. but certificate data never updated in octopus.

**Comment by zentron** [comment]
This issue should now be fixed as of https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/619
