### ISSUE TITLE
Support for project triggers

### ISSUE THREAD

**Issue by hans-m-song** [OctopusDeployLabs/terraform-provider-octopusdeploy#607]
**Is your feature request related to a problem? Please describe.**

Is there any plans for support of project triggers with this Terraform provider?

**Describe the solution you'd like**

To be able to create triggers for runbooks and deployments using this provider

**Describe alternatives you've considered**

I have created a sample resource [here](https://registry.terraform.io/providers/axatol/octopusdeploycontrib/latest/docs/resources/project_trigger)

**Additional context**

**Comment by tleed5** [comment]
Hey there, thanks for the request. Currently the provider already supports deployment target project triggers so I've started work on adding the scheduled project trigger and should hopefully have it done within the next week or so. Ill update here when the change is merged 😄

**Comment by tleed5** [comment]
We just rolled out the scheduled project trigger resource in `v0.18.0` of the provider. This works for both projects and runbooks, you can see how to use it on the docs here https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/project_scheduled_trigger .

Let us know if you come across any issues with it 😄
