### ISSUE TITLE
Support name field for octopusdeploy_feeds data resource

### ISSUE THREAD

**Issue by hans-m-song** [OctopusDeployLabs/terraform-provider-octopusdeploy#653]
**Describe the bug**

The `octopusdeploy_feeds` and `octopusdeploy_static_worker_pools` data resources do not filter using the `name` attribute.

**Steps to reproduce**

Given I have two "Docker" type feeds name "foo" (`Feeds-1`) and "bar" (`Feeds-2`)

```terraform
data "octopusdeploy_feeds" "foo" {
  name      = "foo"
  feed_type = "Docker"
  skip      = 0
  take      = 1
}

data "octopusdeploy_feeds" "bar" {
  name      = "bar"
  feed_type = "Docker"
  skip      = 0
  take      = 1
}

resource "terraform_data" "feeds" {
  input = {
    foo = data.octopusdeploy_feeds.foo.feeds[0].id, # Feeds-1
    bar = data.octopusdeploy_feeds.bar.feeds[0].id, # also Feeds-1
  }
}
```

**Expected behavior**

The `name` attribute should filter results.

**Logs and other supporting information**
Add the output of running `tf plan` or `tf apply` along with any errors in the Octopus Server logs.

N/A

**Screenshots**

N/A

**Environment and versions:**
- OS: `OSX`, `Linux`
- Octopus Server Version: Cloud `2024.3`
- Terraform Version: `1.6.2`
- Octopus Terraform Provider Version: `0.18.1`

**Additional context**

`name` is advertised as an attribute of the `octopusdeploy_feeds` data resource.

The api supports `name` as a filter, e.g. https://samples.octopus.app/swaggerui/index.html#operations-Feeds-getFeedsBySpace

However the data resource does not use this field in its query: 
https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/blob/main/octopusdeploy/data_source_feeds.go#L25

**Comment by IsaacCalligeros95** [comment]
Hey @hans-m-song sorry for the slow reply on this. This is an issue with our go client which does not support the name field on the feeds search. It does still support the `partial_name` field which should work for now. I'll be pushing a fix soon but we've recently been migrating a number of resources from plugin SDK to framework and the latest releases are still beta versions so a public release will still be a couple of weeks away.
