### ISSUE TITLE
Destroying a Docker Registry feed in a non-default space fails

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeployLabs/terraform-provider-octopusdeploy#745]
**Describe the bug**
When performing a destroy, Docker Registry feeds in the non-default space fail with a Not Found (404) error.

**Steps to reproduce**
1. Create a non-default space.
2. Use TF provider to create a Docker Registry
3. Perform a destroy action

![image](https://github.com/user-attachments/assets/77560d0c-53ca-4eb6-9506-32e30f7e1249)

**Expected behavior**
The docker feed should be destroyed.

**Screenshots**
These requests match the 404 returned by the tf apply -destroy command.

The requests do not include the feed space IDs in the URL.

![image](https://github.com/user-attachments/assets/e8f1eb2b-1bb3-4a01-b62c-bfb836de151a)

**Environment and versions:**
- OS: ubuntu (GitHub runner)
- Octopus Server Version: 2024.3.10248
- Terraform Version: whatever is configured by the setup-terraform@v3 action
- Octopus Terraform Provider Version: v0.22.1

**Comment by benPearce1** [comment]
Seems to have been fixed by https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/702

**Comment by benPearce1** [comment]
Fixed in `0.30.0-beta3`
