### ISSUE TITLE
Data Resource: octopusdeploy_accounts - Warning: Deprecated Resource

### ISSUE THREAD

**Issue by Aussie007** [OctopusDeployLabs/terraform-provider-octopusdeploy#789]
**Describe the bug**
When using octopusdeploy_accounts as a Data Resource, receive the following for `tf plan` or `tf apply`

```
Warning: Deprecated Resource
│
│   with data.octopusdeploy_accounts.my_aws_account,
│   on data.tf line 5, in data "octopusdeploy_accounts" "my_aws_account":
│    5: data "octopusdeploy_accounts" "my_aws_account" {
│
│ Use an account-specific resource instead (i.e. octopusdeploy_aws_account, octopusdeploy_azure_service_principal, octopusdeploy_azure_subscription_account, octopusdeploy_ssh_key_account,
│ octopusdeploy_token_account, octopusdeploy_username_password_account).
```

**Steps to reproduce**
1. Create an `octopusdeploy_aws_account` resource
```
resource "octopusdeploy_aws_account" "my_aws_account" {
  access_key                        = "AKIA1234567890123456"
  description                       = "AWS Account Access"
  name                              = "My AWS Account"
  secret_key                        = "asdf1234qwer5678zxcv9"
  tenanted_deployment_participation = "TenantedOrUntenanted"
}
```

2.  Create an `octopusdeploy_accounts` data resource

```
data "octopusdeploy_accounts" "my_aws_account" {
  account_type = "AmazonWebServicesAccount"
  partial_name = "My AWS"
  take         = 1
}
```

5. Run `tf plan` or `tf apply`

**Expected behavior**
No warning as there is no option to create a Data Resource of type `octopusdeploy_aws_account`
_or develop an `octopusdeploy_aws_account` data resource type_

**Environment and versions:**
- OS: `Windows`
- Octopus Server Version: `2024.3.12766`
- Terraform Version: [e.g. `1.9.5`]
- Octopus Terraform Provider Version: [e.g. `0.30.7`]

**Comment by domenicsim1** [comment]
We should remove this warning, the generic account data source still has value.
In addition, account specific data sources could have value as they will only expose the relative fields and complement the account resources nicely.
