### ISSUE TITLE
Can't create Tenant Common Variable without link Tenant to a Project 

### ISSUE THREAD

**Issue by HuyPhanNguyen** [OctopusDeployLabs/terraform-provider-octopusdeploy#790]
**Describe the bug**
When attempting to create a new tenant common variable, the operation fails if the tenant is not linked to any project. This occurs because the tenant variable set relationship, which links the tenant and library variable set, is only created when a project and tenant are linked.

**Steps to reproduce**
1. Create a new Terraform configuration with the following resources:
   - `octopusdeploy_project`
   - `octopusdeploy_library_variable_set`
   - `octopusdeploy_tenant_common_variable`
2. Ensure the tenant (specified in `var.tenant_id`) is not linked to any project
3. Apply the Terraform configuration

<details>

<summary>
Terraform Configuration</summary>

```
resource "octopusdeploy_project" "test_project" {
  auto_create_release                  = false
  default_guided_failure_mode          = "EnvironmentDefault"
  default_to_skip_if_already_installed = false
  description                          = "A test project created with Terraform"
  is_disabled                          = false
  is_discrete_channel_release          = false
  is_version_controlled                = false
  lifecycle_id                         = var.lifecycle_id
  name                                 = "Terraform Test Project"
  project_group_id                     = var.project_group_id
  tenanted_deployment_participation    = "TenantedOrUntenanted"
  included_library_variable_sets       = [octopusdeploy_library_variable_set.common.id]

  connectivity_policy {
    allow_deployments_to_no_targets = false
    exclude_unhealthy_targets       = false
    skip_machine_behavior           = "None"
  }
}

# Library variable set resource
resource "octopusdeploy_library_variable_set" "common" {
  name        = "Common Variables"
  description = "Common Variables for use across projects"
  space_id    = "Spaces-2"

  template {
    name             = "Common.TP.Environment"
    label            = "TP Environment Parameter"
    help_text        = "Environment identifier - typically prefixed to resources"
    default_value    = ""
    display_settings = { "Octopus.ControlType" = "SingleLineText" }
  }
}

# Tenant common variable resource
resource "octopusdeploy_tenant_common_variable" "tenant_common" {
  library_variable_set_id = octopusdeploy_library_variable_set.common.id
  template_id             = octopusdeploy_library_variable_set.common.template[0].id
  tenant_id               = var.tenant_id
  space_id                = "Spaces-2"
  value                   = "Test Common Variable Value"
}
```

</details>

**Expected behavior**
The tenant common variable should be created successfully, regardless of whether the tenant is linked to a project.

**Actual Behavior**
The creation of the tenant common variable fails with an error.

**Screenshots**
![image](https://github.com/user-attachments/assets/7032aad1-4343-4bfa-8618-8768482dbaa0)

**Work around**
* Link tenant to project by using octopusdeploy_tenant_project resource
* Add depends_on attribute on octopusdeploy_tenant_common_variable resource to octopusdeploy_tenant_project 

<details>

<summary>Workaround Configuration</summary>

```

# Tenant project resource
resource "octopusdeploy_tenant_project" "tenant_project_env" {
    tenant_id = var.tenant_id
    project_id = octopusdeploy_project.test_project.id
    environment_ids = [var.environment_id]
}

# Tenant common variable resource
resource "octopusdeploy_tenant_common_variable" "tenant_common" {
  library_variable_set_id = octopusdeploy_library_variable_set.common.id
  template_id             = octopusdeploy_library_variable_set.common.template[0].id
  tenant_id               = var.tenant_id
  space_id                = "Spaces-2"
  value                   = "Test Common Variable Value"
  depends_on              = [octopusdeploy_tenant_project.tenant_project_env]
}

```

</details>

**Additional Notes**
This workaround ensures that the tenant is linked to a project before attempting to create the tenant common variable, thus creating the necessary tenant variable set relationship.

**Possible Solution**
Consider updating the provider to automatically create the tenant variable set relationship when creating a tenant common variable, even if the tenant is not linked to any project.

**Environment and versions:**
- OS: Windows
- Octopus Server Version: latest 2024.4
- Terraform Version: 1.9.7
- Octopus Terraform Provider Version: v0.30.7

**Comment by mjhilton** [comment]
> Consider updating the provider to automatically create the tenant variable set relationship when creating a tenant common variable, even if the tenant is not linked to any project.

Unfortunately this isn't possible, because the linkage to a Common Template goes _through_ a Project. The graph looks like this:
```
Tenant --connected to--> Project --includes--> Library Variable Set
```

Instead, we've opted to do a bit more detailed detection and logging to help users understand what they need to do to self-solve. A couple of examples of the errors you'll now see:

```
│ Error: Tenant doesn't need a value for this Common Variable
│ 
│   with octopusdeploy_tenant_common_variable.common_variable["Tenant1"],
│   on main.tf line 70, in resource "octopusdeploy_tenant_common_variable" "common_variable":
│   70: resource "octopusdeploy_tenant_common_variable" "common_variable" {
│ 
│ Tenants must be connected to a Project with an included Library Variable Set that defines Common Variable templates, before common variable values can be
│ provided (tenant not connected to any projects)
```

```
│ Error: Tenant doesn't need a value for this Common Variable
│ 
│   with octopusdeploy_tenant_common_variable.common_variable["Tenant1"],
│   on main.tf line 70, in resource "octopusdeploy_tenant_common_variable" "common_variable":
│   70: resource "octopusdeploy_tenant_common_variable" "common_variable" {
│ 
│ Tenants must be connected to a Project with an included Library Variable Set that defines Common Variable templates, before common variable values can be
│ provided (tenant not connected to a project that includes variable set "LibraryVariableSets-61")
```
